import streamlit as st
import streamlit.components.v1 as components
from supabase import create_client, Client

st.set_page_config(
    page_title="Nuss-Checker",
    layout="centered",
    initial_sidebar_state="collapsed"
)

# ─────────────────────────────────────────────
# SVG ICONS (base64)
# ─────────────────────────────────────────────
ICON_PROFIL_AKTIV = "iVBORw0KGgoAAAANSUhEUgAAAQcAAACpCAYAAAAmyviNAAAACXBIWXMAABYlAAAWJQFJUiTwAAAML0lEQVR4nO3dPXbiyBrG8afvmdxOFJu7ArOCayYjweNZQdMraDojazpTNu4VDF5B2yZRNvLdwLV3ADFJswLfoIp2Ib/i+6ME/985Pg1CEtWBHkql+vjw+voqACj616ELACBOhAMAE+EAwEQ4ADARDgBMhAMAE+EAwEQ4ADARDgBMhAMAE+EAwEQ4ADARDgBMhAMA02+HLgAO73EwaEtqFzY/S/opKZc0vG61hnstFA7uA/M5nDYfDH8vsetELijuJd1ft1o/d1gsRIBwOHGPg0Fd7qI/W/HQB7mQ6G+7TIgD4YBpQNwWNl8tefjEH3tLbeK4EA4o9TgY1CTVJDX837zAICSODOGApT0OBueSbvzfHyW7TSR1uN2oPsIBa/G1irakjuz2iidJN9QiqotwwEZ8baIjOyQmktrXrdb93guGjREO2AofEreSPhoff7tutXr7LRE2RTickCxNapLqwd/5nN1zSUNJebM7Hi77HY+DQUNSX9JF4aO761arvex5cHiEw5HL0qSht0bE4gW7rJF8B6hmd7zwFsHXIvp632h5J9dYSTtEBRAORyhLk3O9NRauGwhlRnK3D/1mdzz3In8cDG4lfS5sfrhutW62XCbsAOFwZLI06UjqaXGPx4nc+AlLfcnjb5vdcW/eTiXds7nFqADC4Uj424e+ymsKI7lxEblcO8LcX31f+6hr8S3JSFK72R3nZecqCQgaKSNHOByBLE16kr6WfHwn9wtfVktY9jvqcrcpN7JrFd+b3XGn7PiSgPiTx5zxIhwqzP+638vu1vxdUm9RDWHN7+zIDqMXSY2y73wcDHqF4yaS6gwHjxPhUFH+Is0lXRY+epKr5g93/P01uduYYjCNJN2U1VQeB4N7zT7FeLputRo7KCI2RDhU0Jxg+LaogXAHZelI+quweSJXg3gXEP4x57Nm2zC+XLdaxVGhODDCoWJKgmEi92udr3ieht46REnuoh3K9WdY+nbEN4bea7YtYiSpbp3Hd5T6p1D+Gv0f4kI4VEyWJrlmq/Klv9Ilx8/r5hy6k9RZNiR8g2Wu2YB4aXbHdWt/ow/E9+tWq7RBE/vHBLMVkqXJrTYLhrpczWBRMMjvM8zSZKkOS74MDV+mqUtfZkuvsO9nP9ITkSAcKsJX3Yu9DUsb/kqO/59Wmw7uTNKPNQIi9Nl/9wx/C9ErbKbmEBHCoTr6hffflm1j8E8WNulP0PfnWMgHxBfj+HeDvHwj5CjY1F63gNg+wqECfCensHX/acWnEj2tPoFs6Ezvw6lUszu+lXukOnWh8lpBeN7hiuXCDhEOkQs6HYXaKxxf03JtDItcLVt78NqabVPoWLUHucbRT3IdqHicGREWtYlfcYalbyt2cNrmCMi23rcTmJrd8dA3Rk57RJ7J/V9mjvdtD32tUDPBflBziF87eD2d4XkVja2VZPVz3apQe9heUbBrhEPE/FOCsK1hpc5J3rzZnnbKlzUMs7Nln3zg8LitiFvxQqriPXlfs4OtblR4chIsqnMlZq2OBjWHuIXh8LLpsOtD8O0jL8Emq+bQ01vnritVMwSPDuEQKd+bMWyIXLefQr55aX5ZN5z6weszo1NU8dantub3YIsIh3gVxyTka55nm5OprFuG4nHF/1sxdJgAJgKEQ7xmLqBVRlwWjnvWbC/EdY2WmXl6ThlCM/83P+Dqi9zK3Z8Yvh0HGiTjFV5Am17cbc0OkV7Hpo8hn/TWrlArfugDgVCICDWHahhucrCvdXzf4BR369YaStS2eC7sCOEQr7DmsPFjPT/5690ah941u+P2pt+v2XaHba+lgR0gHOIVPqnYyiNMf5H/qeVuUyaS/txSMKCCCIcT0+yO75vdcU1usNODZoNi5Ld9klTb8q0EKoYGyXhN9FZ7qG375M3uuC8GO2EOag7xCm8laocqxBY1gtfbeLSKHSMcquFgg6d2ZHjoAmAxbivi9ay3fgHF9SnW5rsuT//OjXO/yD0dySU9b7HdIZwYd7ilc2KHCId4DcM3WZo01u0lucQ6l6FpWFz5Yydy3Zn7G35/aLjOebBfhEO88sL7urFtLn9RFqezX9WZ3DRzH7M0eZJbf3Olcuj9JDGrHo8DoM0hUn48QjiLUnuV4/0Ubf/TZsFQdCXpnyxNbkvmgyzTCN+sWwPBfhEOcQvv9y+XmeA1S5NalibPer/GxTZ9lpQbtwtWec41u3Duw85Kha0iHOJWbAxsz9vZX6zP2mID5hyXWi4gigO26FhVEYRDxPyTgmWmdy9bq3LXzrQ4INrB62njJiqAcIjfzAStMoZOBytv7zMYpqYBUSt+kKVJR5tPkIsDIRzi9256d6P2cK/DBMPUmQo1Al/GXmG/4ntEjHCInDW9u4IxEX6pvG0+kVjXpS/LVE+zgXW34mI8OLAPr6+vhy4DFvC/wkPNXmyf5Hsx6rC1hqJ/y/XJ+BFsm8iN8uSWokIIh4rwi8EUL7j/SmodpkSlBpL+o9nA+uIX10WFEA4VkqVJX9tZFHefHprdMatcVRBtDtXS0ewCMbEbacWenYgH4VAh/p69rdmnF7GaSLqhnaG6CIeK8WMuGoo7ICaSGlVcvg9vCIcKijwgCIYjQThUVBAQMbVBjEQwHA3CocKCgIhhpOODpDrBcDx4lHkkfD+IvvbfIWoiNwEM/RiODDWHI+FHcNa03qpW67qT6/lIMBwhag5HyI+Q7Gm5OSPXcSdXWxju4NyIBOFwxPyYjBv/98eC3Rd5kBt5ybDrE0E4nAgfFHW5Bsy63LT0ZaM5n+Smp3/2fzmBcHoIBwAmGiQBmAgHACbCAYCJcABgIhwAmAgHACbCAYCJcABgIhwAmAgHACbCAYCJcABgIhwAmAgHACbCAYCJcABgIhwAmAgHACbCAYCJcABgIhwAmH47dAFQXVmaNKavm91xHmw/t6ayz9JkOiX+zP6IE+FwYFma3MqtIzHPUFKuSBaU8Wtg5JIug80f/Ge5pKssTV7kVtwOy3urt7UyPuy+pNgE4XB4dZUvLjN1JemjpE6WJsULbq9KgmH6WUNv/5dLuZW2+nsqGraMNoe4vMitNhX+hS4lDX31/FBu9BYME0nfJX3y74eFfYvvUSHUHOLSse7F/cK493IX5Zl/XdtnwQLh9943u+PO9E2zOx5mafK7pLbcEnr5fouGbSIcKsBfdA25X+IzSRf+9iI/ZLnkbi9m+DK9247qIRwqotkd/8zS5F6u7UFyC+Lm0q+aRc3vN902XThXkp5Lnh78Os4bNrvjofX9wfnC/c/DJxZGmfOyzxA/wuE4tCV99a8/ZGnSk9SRq2VI0u8Kfs39Bd2T0RCapclI7vbmvvBRXdI/hW1/LSgXTyQqjAbJamkEr3NrhyxNhnJBcVbyeVvuIi97QnIh6UeWJv31iohjQc2hIvzFeuHfTlT+JGC6z0iu4fLndF9fY/g72HckFzLPcrcLN8HxH7M0GTa7455/P5T0TS6gpsFyZ5Tjq3AUCIe4tI17+JpclT7sV3Bb1jbg3TW747axvR+8nkiqh20R/nYkD77ra5Ym/WZ3PG2L6Pl9puHQL7YrZGlCOBwJwiEuHxfvoofg19wysoLB9424CDa960zlGz0bcjWJ6b43cj0bcWJoc6iOF0m/N7vjmwX79Uu2h8c9NLvjZ2snHxjhORpLlg9HhppDXL7I/WqHfpZdyCWW2XfRPrne2g7OV/huHBHCIS7PW+gbcPCBWTgO3FacpkVjMxrBa8LmRBEOpyPs1PRH2eAt3xOyHWzKd1gmRIxwOBG+3WIUbMp9EPwSDMcO+1P091E+xIc2h9PSkfTDvz6T9OwnZxnK9adoaPZxZy+GyWVwGNQcTogfL/Ep2HQh17fiq/83DIbvze6Y/g0njHA4Mc3uuC83EKs4kczUk1x/ik7J5zgRH15fXw9dBhxIYVi3VDK0G6eJcABg4rYCgIlwAGAiHACYCAcAJsIBgIlwAGAiHACYCAcAJsIBgIlwAGAiHACYCAcAJsIBgIlwAGAiHACYCAcAJsIBgIlwAGAiHACYCAcAJsIBgIlwAGAiHACYCAcAJsIBgIlwAGAiHACYCAcAJsIBgIlwAGAiHACYCAcAJsIBgIlwAGAiHACYCAcAJsIBgIlwAGAiHACYCAcAJsIBgIlwAGAiHACYCAcApv8DLz/j0j0lREwAAAAASUVORK5CYII="
ICON_PROFIL_PASSIV = "iVBORw0KGgoAAAANSUhEUgAAAQcAAACpCAYAAAAmyviNAAAACXBIWXMAABYlAAAWJQFJUiTwAAAMM0lEQVR4nO3dTXLiSB6G8bdmeu+aE5g+QXkOQLT6ALg8O3ZFnWDEmoWphWOWqE7QeOdd2+YADeEDtH0DfIKxDzBRs8ikLdJ/QAIBKXh+EUQgWRLpBS/5pdSHHz9+CABCf9t3AQDEiXAAYCIcAJgIBwAmwgGAiXAAYCIcAJgIBwAmwgGAiXAAYCIcAJgIBwAmwgGAiXAAYPpp3wXA/t2PRh1JHb/5IunRv3+UND1vtR6N03DgPrCew3HzwfBbgUMnksaSbgmL40A4HLkS4ZD3KulWUkZQHC7CAWGz4kzSSYnTn+RCYlhtqbBvhANM96PRR7mgmL0SSadLTnmW1CckDgfhgMLuR6NZSKRaHBRPktLzVmu8o2JhSwgHrOV+NErkmiJfFhzyXa4m8bKrMqFahAM2cj8aNST1ZYfEk6QOnZb1RDigEr7JkUn6JfjTq1wzY7jzQmEjhMORabZ7iaRG8Mqb5l8PN1fjMte/H41SuZpEOOLx7bzV6pe5FvaLcDhwzXavIenCv8Jf9aImcvMabh9urqarDva1iKGkT8Gfrs9brc6aZcCOEQ4HytcQUkmfK770RFL2cHN1u+wgPxSa6X1fBAFRE4TDgfGhMNTyOQl5k2C76CSoZ0lpgZAY6n1AfD9vtdKC5cOeEA4HwjcfhlredLiTuz/icVVfgg+Z2byGRIsDYyKps6y54fshBsHur3RSxo1wOADNdq8jV4W3vsATScOHm6thBZ/RkR0+r5L6DzdX2aLzF9Qg/skwZ7wIh5prtntD2XMMJnJf2HHFn9eQCyKrL+NarqlhTnwyAuJZ0hkTpeJEONRUs937KNdECEcEnuWq+eMtf34iu2/jSVKyJCAeNV/mu/NW62IbZcRmWAmqhpYEw7Wks20HgyT5zzjzn5n3SdLYl9FyIdcMmfl8PxoRDhGi5lAzS4Lha9l+hWa7N+twnH2RXySNH26uSvUD+P6IcE2IhTUIHwa/53bRvIgQ4VAzC/oYSgVDs93ry3UuLhrufJbrxOyXuGYiN1Eq3yl693BzZdYK7kejW833WzCDMjKEQ4002z1zSLBoMPiawlDvax2LPMn1XxSqSfjr/xns/maFjL9h61FvYfIqqUHtIR70OdSE/+JtGgxjFQ8G6a3/4KzIwT5Evga7L63zz1utqdyox8yJ3IxORIJwqI9wDsH3EsHwUe+r/EWdaHkH4xxfpu/B7uGCwzPNd04SDhEhHGrAd/jlJx89Pdxclfki9VV8OrXlRO/DaSFftqfcrk++STTHNyHy16VJERHCoR76wXbhYPC/+P+uoAxf/ASoojrBdn9B7SOTq2m8qkQAYfsIh8j5WkP+V/+65DyGToXFKTwfwfc/5OdAnFhlOW+1Xs5brfS81fqoxc0P7AHhEL/+iu1VCnUmFpSUPD6s4Syt8TBSERfCIWK+lz+sNUxLXqZRWYHeJksV4idA5WsPp812j9mQNcGzMuPWCbbr2CYPF3y5kBs5+UtuYZiG3NwHVq2OADWHuOV/ZZ/LTmuOgS9zfuTCqjkM5QLkF7nOU4Y0I0A4RMqPDOSbFEtXXFqiykCZrnlevuwnxqSosLmSrPk5qBDhEK8k2B6veZ11z6vyWuF5SbA9rehzUCHCIV6NYHu8zkX8Go/PmxZG0uu6q0kZQ6+NYDuV67icyK0v2V/nc1AtOiTjleTePy9aPKWgvt7fUr3ONTbxpLf7OuaaFb7zsbPh9VExag71MN3kZP+LHy7KUsbdsvUhC8qHW6khUewH4RCvRu79xsN6DzdXHa0XEBNV86ue7xgtc2co9oRwiFd+pKKSEQcfEN80fyfkMt8ebq4WrgdZEvMWaoZwODJ+4ZUzuZB4Mg55krsR6ucyK0Hh8NAhWQ+NKi/mp2D3/Ws2p0JrTM3GASMc4jXR2xoOjW1+0I5CIT9CUbRZgz2iWYFdyY9Q1G4a+DGi5hCvqd5qDsuef1mKb0IkcrWRZMFhj/41rrBWka850DlZA4RDvB6Vu5ux2e6drXvjlV+BqeNfRYYR/wqjZrv3LHdj1HDdoPCBlF+/kppDDRAO8Qq/QImxbykfCuEt02WdSrqUW0X6Wu75m9OS10iC7fEG5cGO0OcQKeN+hKTM+X5B16k2C4bQF0mP1mKxK4S3aVNzqAEeahOxZrsXPhXqH6smJPnawlD2U7CrNJF0UbA8/82f93BzlWyzYKgGNYe4hWs4dJYdnHuO5raDQXL9EkUeeBPWGtZdlwI7RjjE7VYFH/qy5AG72zR7IlZjyTH9YHu4rcKgWoRDxHyVPf9Le+qXqp+zp2CYOZF0az2TYsGy+gxj1gThEL9+sJ0ZX8Sh9nun4ycFNQJfxn5wXLiNiBEOkfPDhuHDYfqzDb/U+y76GFb5HIxipNp8WX3sEaMVNeDb9PnH1UvSr37fVOs9IHcbXuVmXjYk/Rn87WfCoV6oOdRA7i7KvFu/L5ZgkFxZ/qP3k5y+EQz1Q82hRprt3ljz91n8T9Lf91OahcIyPT3cXFX5SD7sCDWHernQ/NBmbMEgzZfpVSUevou4EA414ocBE9VnPYSE5kR9EQ414+/MrMPj4r7W8fF9eEM41JBfav6r4q1BfF33ATiIBx2SNebvaxgrnhGLV7mbscb7Lgg2R82hxny1/Uz2KtK79iTXxzDed0FQDWoOB6LZ7vXlFmXZh+8PN1d16AdBCYTDAfHNjEwVrjm5wkRSSsfjYSIcDlCz3UvkZk9uKyQmcsvFjbd0fUSAcDhg/p6MVG4i0unyo1d6lpuyPaSmcBwIhyPhmxyJXAfmmVbf4v2k+SXqCYQjQzgcOV+7aPjNF0IAM4QDABPzHACYCAcAJsIBgIlwAGAiHACYCAcAJsIBgIlwAGAiHACYCAcAJsIBgIlwAGAiHACYCAcAJsIBgIlwAGAiHACYCAcAJsIBgIlwAGD6ad8FQH2l3fSj3DL3ygbZuMDxZ5I+Fj0e+0U47FnaTTt6Wxp+mdtskEWzbHzaTYeSvuR2fQj2X2eDrBOcln9U34ftlhCbIhz2r6Nij627TLvpRNJFNshetluk5dJuOpZRZl8zmAXGl7SbjrNBNtxh0VAh+hzq5RdJY1+d34u0m15oPhgmkr7592Fo7TXEsBlqDnH5NWyL+yBI5Krkp3KPsRvLt/X3IP+5d9kgu5htZINsmnbTrtyzOcfZILvdeelQGcIhcr4JcZt209lzK08kfUq76VkEfRDvvvzZIMvkggw1R7OiJrJBNpWrMcxc2EeWk3bTs7SbJr6/oKxpFWVAnKg51IvZhk+7aV/SpSRlg+yDHwHpyzVDpKC5knbThv/7hVxNZLZfku4kZUbzJpH0R/DRf/hzTNkgY0Sixqg51EuSe282KXzz4ze9BUP49wt/7hflgiHns9yXvr9JQVF/hENN+NpA/gu/qL/hU+79xL9e/DXOJP2u+VCYjTZMgutc+s+cmRrHXft9+RcOBM2KuJwZ1fREboTgc27fd98HscidpNQ4Jt9R+CopyXdq+pGRsd4CJku76W02yF78tfq+RjEbyhwazY/LJeVCjVBziMtArl2ff11qPhgmcv0FizxL6oTB4GsN+fkJSTja4UdGEn8NydUwOuX+BRwKwqE+XiV1s0GWrJghOVzw9yT3frJoGHQ2dLrgPBwRmhVx6cruS3gpMadhumB/flbleMU1xpL+bZyHI0I4xOWxgrsVpxWUg2nPoFlxpFZNeEp2UQjEjXA4HuPc+2TFzVudBefhiBAOR8I3V1795omMuzvTbvrR346dn08x3EX5EB/6HI5LKjd7UnJzGR794ixjuaZER/PBsGo+BQ4YNYcj4hdeuc7tOpWbRzGbT5EPhutskC2+cQIHj3A4Mn7ptn/pbaJTaDaforOrMiFONCv2L9XbXIJ112cY6q3jcOU1/CIst37WZOI//0XFhlJXfdavS87N/6+I3IcfP37suwwAIkSzAoCJcABgIhwAmAgHACbCAYCJcABgIhwAmAgHACbCAYCJcABgIhwAmAgHACbCAYCJcABgIhwAmAgHACbCAYCJcABgIhwAmAgHACbCAYCJcABgIhwAmAgHACbCAYCJcABgIhwAmAgHACbCAYCJcABgIhwAmAgHACbCAYCJcABgIhwAmAgHACbCAYCJcABgIhwAmAgHACbCAYCJcABgIhwAmAgHAKb/A4Vg7L01GlnRAAAAAElFTkSuQmCC"
ICON_SCAN_AKTIV = "iVBORw0KGgoAAAANSUhEUgAAAQcAAACpCAYAAAAmyviNAAAACXBIWXMAABYlAAAWJQFJUiTwAAAORklEQVR4nO3dS4hj6XnG8X87HeOQwi2DZZoQpmUzOMYYWgMhDM5An84iPhBLloMhEByPGkLwwjA1G0d4M5pFQNiBqQlZeDdq8MKYQKpLBGRjsMqLMA4Eqs0Y92LIqEIYBssXldMYxxg6i/c9ra9Ub3VddZ3nBwdJR+em7jrP+W5HuvLo0SNERKa9Z9EHICLLSeEgIiGFg4iEFA4iElI4iEhI4SAiIYWDiIQUDiISUjiISEjhICIhhYOIhBQOIhJSOIhISOEgIiGFg4iEFA4iElI4iEhI4SAiIYWDiIQUDiISUjiISEjhICIhhYOIhK4u+gDE9DvlElAFskvc7DhvjbYucXsX1u+UG9jnvCx7wF7eGg0vcZsCXNGP2ixWv1POgE3gMzPaxd28NWrOaNtn0u+Um8BrM9r8fWArb426M9r+u47CYYH6nfIW8MKMd3MAVJfhytrvlPeAmzPezS7QyFuj8Yz3s/bU5rAg/U65y3yCIVuGYHAZdoWfpVvAwKtpcgEqOSxAv1NuAy9Nzd4FusBgiU7mpeYBkAEN4Pmpt3fz1iib9zGtE4XDnPU75Qrw1tTsF5et4XDVeNvNNnAtmX1HbRDnp2rF/LWnXr+sYLi4vDUaYCWIVHv+R7I+FA7zl/4B7+etUXtRB7JuPCDuJrNu9Dvly+w2fVdROMyR/6GmxV6VGC5fd+p1toBjWAsKh/mabkHfW8hRrDEvPaTUa3FOCgcRCSkcRCSkcBCRkMJBREIKBxEJKRxEJKRwmK8hdjMU/jhc2JGst/TmLnUXn5PCYY78hqoM2Ge57pZcNxkWEHfy1mh7wceysnTjlYiEVHIQkZC+Q3JJ7fR628DPge8DTWAA5MC/AL8FqNdqujdDZkYlh+VVBX6F3Zw1xL4cZgz8ORYSzUUdmLw7qOSwvJoA9VrtS+nrnV6vUq/Vhos5JNs/wCKPQeZDDZJLaqfX28LuKBwC14H/8beKqkUD+C/gz7BSxhDYqtdq7Z1er+vzHgLfxUocV/1xAyj5cgNfbwN4w7efAd8A3gt8yLcBXpUBXgF+ALSAvwM+iZVuGsC4XqtNf+GKrCiFw5LyExfsJH8d+DXwPqBTr9UGHgC/C/wFdkJv+mMX69tvA/8N1LAxFW8AI+A28HXgAVYaGfp+nse6/yrA94A/Av4A+Dfg933f1+u12uMvT9np9dq+jU1fbxPo12u1L178X0AWTeGw5HZ6vaxeqw3OsPyJ1Y6dXq8EUK/Vnvj17cct5/NL0X6K/Xv1Y3zccrL8FA5LyksGFezKnmG9FRXgGeBrwDvAc9g3S13BShZf99W3gf/AGjTfBzwLvAl80N9/HehgpYvfAX6WLPcjrITRwEogvwf8vR9DUS3Z8GWbPo19qvj2x8DH/PE6VmrZwEo121gJo518pgyonhRWMl9qkFxeJezkgsPDrK/443PYSfXPwKd9mRw7GcfA/2En3gN//UOsfWKABUvd9/EG8AmfB1ZVwZfbq9dqbXgcVg98+hhW3Slh4fAg2S9MQm3o85/GwmHg7/1Nsuy2f45/BP72hH8TmadHjx5p0hRO93Z2Ksnzxr2dndKT5k+vly533HaTedWzHNdx29Z0eZOqFUvKeyvArtBvYCWFnwBvY1faB1hV4ro/gl2ZB1iR/ZfA+4FHWINkBasmVH2Zkk/XsHs9NrCeiQyrdjyLXfnbHP3h2waTBtCHvm7xXY0/Af7E9/GsH2cJq1J0sZJCUWUZY+M3nqnXans7vd4Y+Gayztv+OYoqykOskfRl/0yZb3PzLO0ycjqqViy39/vj09hJkPnrIfDvWDWhqA5UsQDIsRPrf33+W9hgt6IY32Vyspew7tCPAD9l0mYAMKzXahk8rlIMgW8Dn0r21fT5RVdqERBjJm0Rub838OV+6PsqAqMJfHmn1/tK8plfwX4B7CrWVlJhEm579VqtqFqRNHzKZVt00UXTydNJxfPksZq8V0qL+1NVgXB7wXIln45UHfz9LN33aaoLyfKlU1Q/qsX7qkbMf1K1Yknt9HpFsbuJXf0/zORKXTRWVpj0DLyDXaX7TK6k17Er7wZWlP+qz/8yVrwvlLDqwId8nQdYT8dH/PVestzQ99tlMoR7jFUzhtgAqhJWOngT+FxyvEVJ4jvAU9hAq2/5ulf9ODd920M/xj1s3MV/+rZ/BfymOAZ1k86OqhXLq6ibl+q12pWdXq+K1c/vY0Hwa+zEafjrZ7FRjE1/XfQgPIWdTGD19fcwqQaAVVn+FPulqCqTsPmpb6eSLF/Bqgdj4B+Av06Op+TLvQ181Lf7eeDjWAgUVY6HwF8BP8ZO9CJwNrCu1goWDg0/jkFRjfDqzSd822MOB5xctkUXXTTFkxelS+mUvpc8L00X+aMiflqc98dGtI1oexf8HKfuhYj+DRb9//BunlStWFJ+lXzTX25gV+ffYEX/p7Ch0Q+xwUtPY6WIh75O26c/9nWHWGPmELsyv+Ovv4Pds1FUHwbAX/r2vwD8E3aF/kPsql5UV17Hqgddv0djm0npYuDLNJlUgfZ8v8UAqKLnofh8RenlB/55impM5tvLgExViPnSLdvLq4SdNM/5YxXrndjE/t+a2GjJDSb3NXzau/Sq2E1Rn8dOrCZWDdlMtvsAK97fSrbRxnoLBr6PgS//WyYn7JhJN2jTqztFj8mASTikPReFbSbVmeJGrqeZ3NxV3BxWYTKQag/rOSnWkzlRyWHF7PR6jXqtprq2zJzCQURC6q2Ys36nXMV7IvLWaO+k5eXs+p1yCavebOWtUXexR7O61OYwR/1OuYL90d4ABv5aLt8AuAm81u+UGws+lpWlcJivCnYvA/5YWdiRrLebyfPp+0LklBQOIhJSOIhISOEgIiGFg4iEFA4iElI4iEhI4TBf099YpG62S+aDzFL6lqhzUjjMkY+IPEhmbS7qWNbY9L/pYBEHsQ4UDvOX3jR1o98ptxd1IOum3yln2C93FfY1RP38FA7z1556/VK/U1YJ4oI8GKbvVm3P/0jWh+7KXAAvLbw0NXsX/+r2vDVSPfmU/N6JBodLDAC7eWuUzf+I1ofCYUH6nXKXo3/Ql+0AyJalaJ3cLXnzhEUv6j72uRWyF6BqxYLkrVETeHXGu7nGct39OWD2wbCLguFSKBwWKG+NNoHb2B/0rGznrdFwhts/i62TFzm3feBO3hopGC6JqhVLwovcGZc79mGct0azPCHPzNsILvMzDoHBEgXg2lA4iEhI1QoRCSkcRCSkcBCRkMJBREIKBxEJKRxEJKRwEJGQwkFEQgoHEQkpHEQkpHAQkZDCQURCCgcRCSkcRCSkcBCRkMJBREIKBxEJKRxEJKRwEJGQwkFEQgoHEQldXfQByPn4T81vYl/zXvxQzD6wB2zlrdFgQYcma0JfTb+C+p1yE3jthMXuAU39wIucl6oVK8Z/hHc6GO5z9FezPsPRX50WOTWVHFaI/+blW8msu8BmWjoIfsH7Tt4adedxfLJe1OawWhrJ833/Md5D8tao3e+UAZpYyWEpfmFbVo/CYbWUkufHnvR5a9QG2qfZoDdsHtruadspzrJuumzRWOq/D1r8buY4b40UZEtE1YoVMtUQeQBUztvg6NtqAzeCt+8B7eNOVv8x3K1j1t0FGtPH1e+UB8Atf/kBrFRz6/Cq7Pu6CokloAbJ1TJInl8D9vwkP5N+p9zFQiY6ucEaMwfRtvud8hbwr09Y95avWzrmfYBfcDQY8G0OvJQhC6ZwWCH+M/N3k1k3gNf6nfK43yl3/Yr+RN5g+Xwyax94FXjRt73v868BW94IWqybAS8k694HXvZ17yXzb2JtHk9y4Ove9seDZL/dkz6HzJ6qFSvIr94vHPP2PnZybQVF+xIwxE5AgPt5a1QNlhlgJ/gB1hvSDfa7m7dG2dS6bSY9JYfen6pWHKkSeWlhkBzbbQ3kWiyVHFZQ3hptAh/Grvj7U2/fwE7QYVA8bzA5+faBLNj2GLvq38FO4O7Ufm9jJYxmcGjdYF6kOx1c3s6QjstQ1WLB1FuxoryKsQlsJkOp05P/GlZ/z5IGvizZxLE9C7582CjoV/MBPK5mpNvNppc/xnGDs4bJ8ye1WcgcKBzWgJ/MTThS9L/m8zf9dSVZ7Vw9At4G0eZwu4WsIVUr1owX/V9NZmXHLHrmLlAvoewRB8MB1kApa0LhsIL6nXL1hK7CtNh+M3k+TJ5XzrHrbQ63WbwIPJO3Rlfy1qjEpIQia0DVihUyNXDpDsc3AB7XmDdgctVv9DvldtTu4MHTALaL973UkI5tyLzdI5Wd8BFkhajksHqKE3QraRB8zE/s9Aqejj/YZjKe4AY2yjFaf4ANkvpFMhDqidWQpFFU1oRKDiskb426PpbgBla8/16/U97FTuYx1sLfZBIgByT3WOSt0dgbLIuxCM97wHR9/cyna8n6A1932O+U95Ntb/tIyzFWUmkm68kaUDisngZ2MhdtCbeIhyIfYEX/Q70SftdmhUn1ohgXEa3fmKo6bAGv+PObyfPCXdSLsTZUrVgxeWu056Ma0yHH0+4TBEOyjSbwWY4OoCrcBarTIxTz1mgLa+uI9vtqdAu5rC4Nn15xF7nl2tevkPRcnHbI8lR7x5n2KatB4SAiIVUrRCSkcBCRkMJBREIKBxEJKRxEJKRwEJGQwkFEQgoHEQkpHEQkpHAQkZDCQURCCgcRCSkcRCSkcBCRkMJBREIKBxEJKRxEJKRwEJGQwkFEQgoHEQkpHEQkpHAQkZDCQURCCgcRCSkcRCSkcBCRkMJBREIKBxEJKRxEJKRwEJGQwkFEQgoHEQkpHEQkpHAQkZDCQURCCgcRCSkcRCSkcBCRkMJBREIKBxEJKRxEJKRwEJGQwkFEQgoHEQn9PySoI3HH/b4qAAAAAElFTkSuQmCC"
ICON_SCAN_PASSIV = "iVBORw0KGgoAAAANSUhEUgAAAQcAAACpCAYAAAAmyviNAAAACXBIWXMAABYlAAAWJQFJUiTwAAAOL0lEQVR4nO3dXYhjZx3H8W9l1WK33SmUui3VTaG+oNVJb6Rgx6YgUsFMU+lFLoRmvPJC2BMRFQZpKgYqgjmKUPBms+BFLizOJl5506xBKIJuVhGLVpvWIktbJCO1rqV2vfj/T8+Zs89sZ2fyOvv7QNjk5Lxl2Od3nreTXHfp0iVERPLeNe8TEJHFpHAQkSCFg4gEKRxEJEjhICJBCgcRCVI4iEiQwkFEghQOIhKkcBCRIIWDiAQpHEQkSOEgIkEKBxEJUjiISJDCQUSCFA4iEqRwEJEghYOIBCkcRCRI4SAiQQoHEQlSOIhI0JF5n4Ck1qqbRWBlgrscDzrN4QT3d2Br1c0CUJjkPgedZn+S+xNznX7UZr68sERADTg2hUNsDDrN9hT2e9U8/PpM53OeBtoKislRs2KO1qqbNWAInGQ6BQbglAfQIthiep/zUeDptepmPKX9X3MUDnOyVt1sA6eYXmFJbAw6zdGUj7FXFWB7ysc4uVbdHK5VNyfZPLsmqVkxB15jOJVb/AJ2Zd2a4KGuhT6HItYkW80tPz3oNGsTPM41R+EwY144huysMZwGokGnOZ7LSR0Ca9XNCGjlFj+gPoj9U7Ni9iJywTDoNGsKhoMZdJoxsJFb3JjDqRwaCofZq2Seb2NhIRPgozJnM4vuX6DO2KWjcJgh/496IrOorRrDxOVHK0rzOInDQOEwW4Xc60l2Pgow6DTzf9PCPM7jMFA4iEiQwkFEghQOIhKkcBCRIIWDiAQpHEQkSOEwW/k5DZrjMB3Zm7v0N94nhcMM+U1QyRTfjUW7KeoQKWEBcdqnVcs+6MarOVirbhYW6DbqQ0l/44NTOIhIkL5DckF1e70t4E3gF1g1eQh8BDgHvAUcXS+XVWWWqVGfw+IqABdIbztuAZ8Avgx8Cd3NKVOmmsPiigDWy+Wv+uva/E5FrkUKh8VVAVa6vV4JuAHrfb+AhcTPsKbGL4FvrJfLhW6vNwa21svlWrfXa2M1jyO+LsArWDPlNmBlvVxudHu9PjDCmikvYsN+FeBJ4L++jzd8u7eAo1gN5rfA1/1cSliQRb7f4oT/DjIn6pBcUN1eb4gV1iLwDHARuAX48Xq53PE+iVuAu7ECWss8VrDmyEvAp7Hvpxxj4XIv0MZuF29g4QD27c3nsUB4BvgkFiRP+XHw/VYA1svlUbfXewKoYt+hMPZ/H18vl/Nf1ybL6NKlS3os8ONMt1ua9Ppnut3CmW63uAjnq8fiPlRzWFBeMwC7IhewK3wBuAf4PvCav74V+Bg2mtH2bdrAH4APAM8CDwK/AT7s7z8DPIFd6ZP9jrAayJ+Bf/jzEXAT8DWsBoMf9zjwWawWUfNlr/o6yYzE4778DuB3wO2Z45WwWsuWPy8CpfVyWbMZF4j6HBZXEgpj0p/IyxaeIlY4fwS8z5c9iBXKZP1R5vlfgU9hBfICsO77O+rrXZ87/ggLkSex/o4tLID+jX1B7t1+Dg1fXiRtoqxi3+X4KtYkudeX9/2YX/DzKpI2cb7lD1kQqjnInnR7vRrQXy+XR4Hlw/Vyec9Twbu9XmW9XN56p2UyXwqHBdXt9ZIJTkmH5IPAy1iVvwL8Cvgn8FGsJrCCXZn7WPX971iz4mXgdX9/5Pvr+74LWE3gBl/ndtIOyeO+ToOdTYo3STs+K77sKGkNZejn+gxWY3jW34v9vZh0Uhe+n5J3cI6xmtDf/Dz+Avwvcy6vATcCP/DX9/hnKV1NOMneqFmx2G7CCslFrPpd8uUj4I/A50mbDgV/POjrvBurwv8LK1RJtb/tz4/6ejdiIfMe0v4HfJ8VL7Rtf2+ID7H6vxFW+O8lbVJU/Lj3YqFV9ff6vvy4n1uRdAi00e31Gv7+Z4BvYyMnkDZZCljgPAvcCW+PmOz6x5MDmnePqB6L/zjT7dZCoxu7Lc+tU8y9LgXWuWyZLy/M+7Nfyw81KxZUt9cbYVfNCHgeuBmrgo+xGl8yOjAirb4/gk16Sjoxj2JV89uwK3py1W+Tfi1+0vH5MjbykTQ/LgB3+aPvx7yD9Eoek86p+BPwPd/uSazD8g1slOI7fowXsYlU78c6R+/CakY/IZ0KnszPaPtxhn6e57CJV1vAc1jn6Qo26Wu0xz+pXCU1KxZXm7TQ3IkVyBY2oWmEFbghVkAvYs2JsW/zOjZ0eRy4z/8dk44GFLAmykXg49jIw1NYgU1mSb5EGhAl0ubLSmZf38Sq/yXS0YcNbITiLuArfi4l32YV+DVQxgr5q34+Y+zHfpLmUfLZf5/5/Mnf5BF29m+Mdv0LysHMu+qix+QfZ7rd0h6q+7UZncu+J1tNa6KWHnt7qFmxoLwT8LnMogvAf4APAR/ErqqvYFfVW7Ar6Gu+TcMfH8ZGIEakV/+C7+tWrHbwkj9Pmg9fxJoEMfBdP/b17JwH8ay/Hvo9Gh1s1GRMOhJSZOd8i7H/W/NlL2PNjqO+7h1+XhexGkHS6flTbF5ESU2I2VKzYrHdhxWe1/z1e7Hhuy2s8J/DbpA6TtqbX/XnNdIhyKRgPgac8X0eAT7Hzv6FEmlBfgkrpAWs4GYnY13EwqHU7fUK/ryABUqfnb9PWSCt+vex5sIYa27gx73gx0jWz4bKc8BIwTB7qjksmW6vFwFtTTWWaVM4iEiQmhUztlbdTO5HqA06TV39p2StuhkDw0Gn2Z7zqSwt1RxmaK26WcDa8cfwIUAFxOStVTfb2PdTADw86DR1z8Y+6DskZ6uABQPYmH9x91XlAB7NPNffeJ8UDiISpHAQkSCFg4gEKRxEJEjhICJBCgcRCVI4zJeG2SbMJ5llaR7JPikcZmjQafZzi2pzOI3DrpZ7re+W3CeFw+ydyTxfXatu1uZ1IoeN1xpOZha9EAhk2SOFw+zFuden1qqblbmcySHiwdDPLW7P/kwOD91bMQd+U9DJ3OLTQDzoNFUNvgp+v0oN+56IY5m3zg86TfXpHIDCYQ7WqpvJb0ysTvlQC3dzV+6mqGnZxj63gvYA1KyYAy+sJewn46ZpFeh7GM3djIIhCUQFwwEpHOZk0GmOB51mCfu25hemeKjhAtUc+lPc9zbwOAqGiVGzYkF4h9qkOybHg04z3wE6V975Oum+gKG+s2HyFA4iEqRmhYgEKRxEJEjhICJBCgcRCVI4iEiQwkFEghQOIhKkcBCRIIWDiAQpHEQkSOEgIkEKBxEJUjiISJDCQUSCFA4iEqRwEJEghYOIBCkcRCRI4SAiQQoHEQlSOIhI0JF5n4DsT1SPCthX2ZeA7I/W9IF23IpHMz8pOVT01fRLKKpHJWCLnb8Nmfc4EMeteFF+0EaWjJoVSyaqRzXgaS4Phu3c68fQr0zLASgclog3JU5lFp0H7oxb8XVxK14B7gTOZN5/yGsZIldNfQ7LpZR5vh234h0/K+f9DJWoHsXASSwoFuJHdGX5KByWSyHzvH+F9RpAY6/9DZnaxehqOzIPsq1vX8A+11D9I4tFHZJLxPsbkmbFtjcl9ruvEhABD+Xe2gZirtCZuZ9to3rUB+73lzdjAVZjZ9/JWaCikFgM6nNYLtmflj8W1aN+VI+u+herM52a+cINVlgfA0ahfe9x2/47nMIQa/bkO1XvB/pRPVJTaAGo5rBkclfgxHlsZGLrnar2UT2qAD/PLT6LFegKsJpZvg0Ukiu5NwGez72/BYx92xOZ9zbiVtx+h/M+DYywZsWj2c+T70+R2VOfw/KpYAUyW9BWgRbQiurReaxa385v6Ffk7PLzQClTjW94baGPXdWP+fGSbRrZbXMFOIrqUZu0kGe3y9v2475dE/JO1HPJ54nqUTH7vsyemhVLJm7F47gVl4AH2DlsmVgFTu3S5KiQVuW3gVq+fe8FsgTUsWHSdubtCNjw49YCx25knl+padDOF3x/nf08pStsLzOgmsOSiltxn7R9XvFHth/gfqAd1aNszSAbFsPdrsy+/LL3fD9tMjWCzGhFkb0Pm27tsnxI+hnU7zBnCoclly2w3icQkxawVexqHvnrbDj093M8D6MIqzmcuPLasszUrDhE4lY8iltxBevoS5R2Wf2qhwu9mTLCRiRCwZCfwi1LTOGwhPYw1BdnnmdHH0aZ5/uptsfs7LM4DTwM3BO34uuwpo0cEmpWLJHs5KOoHm2ERiTcbsOAQ9LRhBo7OxCzx1nBhjCzowkFdo6QVLzfYy/HlSWkmsNyKZH2JzSuMAGqkXl+NvM82xF4IqpH2fWAt4OhD5yL6tHI50XA5TWNYWC7y/Yny0s1h+USYzWHY1ibv+9zC4akk4lq7OwPeLuJEbfiUVSPfojNTgR4zAOmjfVBlHLbn/DlxK14GNWjbdJmRduPPcZqDDWu/P0SsmRUc1giPjJRIe34O4YV9FPYlOZT7Kz6b8SteCu3jwib/JR4CJsx+TSXdzRu5JoO7V22a2F9G9n9ypJTOCwZL6wFwhOgEtvkpi/n9lHEvilqt9GFs8AD+e09WB7fZZvzaOLSoaJmxRJKahDezi+SFsoxNrmpv4d9NLB+i1Jm+xHQv9L9GXErbnhzouiPsW8zBIjq0QOZc8mKSPstdpsW3Sadf7HrOchs6MYrEQlSs0JEghQOIhKkcBCRIIWDiAQpHEQkSOEgIkEKBxEJUjiISJDCQUSCFA4iEqRwEJEghYOIBCkcRCRI4SAiQQoHEQlSOIhIkMJBRIIUDiISpHAQkSCFg4gEKRxEJEjhICJBCgcRCVI4iEiQwkFEghQOIhKkcBCRIIWDiAQpHEQkSOEgIkEKBxEJUjiISJDCQUSCFA4iEqRwEJEghYOIBCkcRCRI4SAiQQoHEQlSOIhIkMJBRIIUDiISpHAQkSCFg4gE/R/b7kOh1YkCfgAAAABJRU5ErkJggg=="
ICON_REST_AKTIV = "iVBORw0KGgoAAAANSUhEUgAAAQcAAACpCAYAAAAmyviNAAAACXBIWXMAABYlAAAWJQFJUiTwAAARhklEQVR4nO3df2gcV2IH8K9/xXZz1srmJibdyNq75NKExLXaOoEqAa0vR5jjWFmh/1xyf3jVll7zT72GJkyh4PX9gKGheMNBSaGtV/3B+Y9yWVkUhiutV5A7GujFKxTo5QjnVYz+SOZwJOWC7YuT9I/3ZvfN09vVan9qZr8fMF7Nzsw+jXa+896bNzO7Pv/8cxAR6XYPugBEtDMxHIjIiOFAREYMByIyYjgQkRHDgYiMGA5EZMRwICIjhgMRGTEciMiI4UBERgwHIjJiOBCREcOBiIz2DroAFB1XFhZGARQBjG5z0Yr8V5rOZNa6XS7qjV28nwO1QgZDGcCJDlc1ByA/nclUOy0T9RabFdRvZwBUriwsZAddEGqONQdqWRvNilE0r2nMTWcy2Q6LRT3CcKCeu7KwMAEgB1Fr0F2YzmTy/S0RtYLhQH1zZWEhBaCEzbWJU9OZTLnvBaKm2OdAfSM7IdMAlrS3iv0uC22N4UB9JU9lpgGsKJPH2UG58zAcqO9kQGS1ybkBFIWaYJ9DzHiuNQqx481g67MF3bQCoAoxFqJoO351qwWuLCxUEC7fYQ6S2jlYc4gRz7Xy2LX7PQAXAUyhf8EAAOPyM88DuO65VkEGVTMl7eeJnpSM2sJwiAHPtUb/82+/9L8AzuPzzw4NujzS2d17D765RUCUtZ8ZDjsIr62Igd179v/dp5/8+g/06QcOP4w99/QnKz79zUe4/eEvQtM+u3vr4d17D74J4HdaXM12r9mgHmI4RJznWjMAnlenjYylcf/Jl3HPF367r2X59Dcf4YOl1/Crn/9bbdpnd2897LlW3nb8fF8LQx1jsyL6CuoPhx/MYDxd6HswAMCeew7h/idewgOT39HfyrXQ/0A7DMMhwjzXmoDoCAQA7Lv3fjww+d0Blkg4/OA0RsbS6qQExNkTihCGQwR5rpX1XKsM4N/V6bv37Mcvf/wnuH3zncEUTHH0d1/UJ7GzMWIYDhHjuVYWwCWI04YPqu/d2aji4/d/tiMC4sCRTX2QDIeIYThEz5YjCT/95Ne49eHgaw8UbQyH6Elj84VLIQ9MfgeHH5zuT2kotngqM2Jsx1+DrKJ7rpWHGJEIAPjys/+Ae4+eHFDJKG5YcyAiI9YcYuTOxsrcvUdPBjWLfl50RTHEcIiR1f/5bvF4+i/KoWmrqxMQ/RTB/+ObFhwc/QpMXpG5g7BZEXPJZLKSTCYLyWQym0wmUwB+D8CrCN9sZSCmM5kKgFn549x0JlNoNj/1F8NhyMiwyClBMTfI8kxnMkWIe0hmB1kO2ow3e4kgORAqCyCFcDNhCaJqnrMdv9Lq+t76j78av3vr5t/f2bj+zMcfXNsLiCs6R8a+ii8++q22r+xc/pfQuKdF2/HTba2IBoLhEDHKCMlm1gGk9YCQywZ3iALEzVYqEBdvGTsv9+z7AsZPFXDr5jvYuPHfYto9hzAy9tUtx1IwHKKNHZLR08q9FhMQHZAVoHbruCKA09p8U/qCR45NAgBuvvdTAGK05S9//KebPmDjRhm/+r9/xZef/ce2axbyITklWY5FADnZD0E7APscoieNLUZIApi1Hb+o/JzH5mAIOXTfY5h68S08+cI8nnxhHs/k3sV9X/l60w+5/eEvsFLu6L6wedQDakr+TDsEwyFibMdfsx1/wnb8XQAuaG+fsh1/lxoMnmulAJwFgL37R/DkCyXYjo/j3/gBDibGUJ8+X/sZAPYdSOD3/+ifcei+xwAABxNjOP6NH8B2fEzOXq3N+/H7P8PGjavt/jr6xVjpdldE3cdmRfylgxcPPf0yjhx7CgCQPP5NJI9/Exvvv42DiTHsO5AwLvzUH5dx872f1JYDgJGjj+ORZ76Haz8ST7e7dfMdjIydaqdsRYSbNsV2VkK9wZpD/KWCFyNHH9/05sjRxxsGQ0ANhmbTtkuexpwFMA/g3HQmw2dX7CCsOcRfrYNvdflyaKe+tX4Dq8s/xJFjTzXc2YN5ksefDzU7Vpcvd6VwMiCKXVkZdRXDIf7KEKc2E6vLl3EwMYYjx57C6vJlZQd/BZOzVzfVLD65vY6f/FMad+9s4N03XsGRY5MYP/ltfPTB23j3jVdq8/Hy8HjiOIcIknecDq6VUNvscxBPnSrIS7uD+bPYYmzE3v0jePRr38d9X/k69h1IYHX5Mt59429wa/1G07J88ZFv4f4nXjK+x3EO0cZwiJgWB0EtQQyC0gPiNQD71Rn37h/B3TsbTVd2MDFmDInde3/rtcee/+kfosEAKoZDtLFDMnpauTjpBLTBUvL0Zm3Zh55+CZOzVzH14lsYP/lnDVd05Nhkbb5Hnvme+tabz/7lyosQw7jXWy8+RQX7HKInDdGP0OwUw1yDh8jcDl489PTLtYmPfu37SD3x51hd/iE23n8bd++s1zopg47KfQcSSD3xbfz8v/46tK5kMllZXV2dAdD2YAfamRgOEWM7fkU+ryIFcdQ+o7x9DkDFdvzydtd7MDEWCoztSCaT5dXV1XMQD/ClmGCzIoJsx6/KAKhqb7UVDN2QTCYLENdHUEwwHKibZsD+h9hgOFDXJJPJNbR21ShFAMOBuiqZTBbB5kUssEMygrRBUKqs51ppAKXt3AmqB3IArg3w86kLGA4Rs8UgqODMRc5zrU13gtLW0+2i1cjTm3MIn0mhiGGzInpavRNU1jC9m7WJrdaV7+Jn0QCw5hA9aYhBUM0eWDNnO/6mELEdv+S51nPo/InXa7bjNx2pmUwmq8sdfggNFq+tiDD9WZkQd4IqD6Y0m3mupX65eG1FxLBZQURGDAciMmI4EJERw4GIjBgORGTEU5kR5LlWAeJ0ZEp7q+C51raflUlkwppDxHiuVYR4SM0Uwg/RBcTYhykAZXnPB6K2MRziKXhWJlHbGA4RYzt+FuIu083oz8rsO/kYPlV1AMWgDrDPIYJkQARXYKr3btxJoxCz2s/sA4kY1hwiTA6VVu+8NCWv2hwo2d9xXptcGkRZqH0Mh+jTL4C65LnWwO7GJO81UdYmz9mOX+1/aagTvPAqBjzXqmDzVZorEDtptU/FGIW4h6R+BmUdQEp9wA5FA/sc4iE4Wqs75jgGf7OVdWhP3qLoYLMiBmSVfQI7696NwSP52BEZUWxWxIw8g5GDuClMs6di9co8xD0siwP4bOoihkOMea41iv4Nhqqw+RAvDAciMmKfAxEZMRyIyIjhQERGDAciMmI4EJERw4GIjBgORGTEcCAiI4YDERkxHIjIiOFAREYMByIyYjgQkRHDgYiMGA5EZMRwICIjhgMRGTEciMiI4UBERgwHIjJiOBCR0dA88cpzrQK2vk17FeLJUSXeZp2G3dDcmt5zrTKAqRZnXwEww6c10TAbmpqDZgmAXjNQg2McQNlzrR3zODfPtYIUX7QdPz3IskSVsg1hO/6uQZYlCoY1HHK245f1iZ5rTQAoQjyxOgHRxBjtZ8GIdgp2SCpkLSEN8XRoAEh4rjUzuBIRDc6w1hwash1/zXOtEuqPr58AUGo0v3xwbWCt1WaI51opACllUlU+LbvZ+gFgVJtmfEal4TmZDcumlaVROdT1hdalLV8rj1LORmWcQLhmZvxs/TPUWp+6LUy1QX2eBtNa2vaN1h9XDIc2yB0lDyAL7UnWnmutACjYjl9osmwJhs5Rz7UWAWS1L+pVbbYT2rRTEM2fYB0pWbYz0Miy5WzH18MuC+C8fH1BLq+bUD53EaKGZVr+lPKk72Db6GWcAVCA6NvRy2jaBqHP8FzrSxDNvylt2UYdyfo21KeFfmfPtbKyfPrfdh1AvtHfNm7YrDBLK69DXzS5c5cBnIX5EffjAC56rlXU35BHyioanzWZAlCRn7Ftcv0VGIJBKdvrPW4qFSB2YtO2CXa812EIBmkKojO42TaowLwNg47ktp8s7rlWHsAlmMufgPjbMhyGkdyp1S+ufhQqQRy9A/MAZiGOPkvK9DOGL1EW9S/dOoBX5bKvQpw+hXxfXe6C/BdYUaZdgAibQFFZ/wqAOQDn5P8ryny9/HIH2yb4/WpllLWaS8q8S6hvg3ll+jhEzaORhLL+UxC/47ryXlmbX9+G6rQLwfwykM4r8yzKdZ/TyndW/i6xNqzNiqyhHZqCqDqrO/4FtXorj3rqEWvWdvyi8nNehktw5D7ruVZBWYd6xM6py8rl8hDhU6v2246fl+8HX9pqME0lv6xq2WcM/QLX5Y/jnmtN9PA07TxE00DvZ8gqr/VTskV51A5+T/U93ToA9TRzWfYTVSDCISFPQ5cB4zaEaRsi/PdZ0cpXkOUbBVBs1DcSJ8MaDo2q3ap5wxdI/fLMacEAALAdPwieoPaRhjii60LVZvlFb7u6bzt+VbbFZ5T16e8voh5uvTpFuwJzMMB2/LzciXMw92sETZKtFBv8fkWI5h4gtnu55VIbeK6VUkOgQaDE1rCGQzNLaDAOAuGj2ag8kmwlpbwuox5MFz3XykHUEsqGTsJtk1/kAhDq3Q/OCASve63cbOi53KmzQOhsQPB/q+UrN5jeaU2ohHqzZxzAdRmoJYgh9dUO1x8pwxoO5xD+IpVQb6sXm5yyUjupTst/25FDuOkyDnGkOyt7wksQveHVba63RgZWFo07/Hqt6Q7a7GzKNjQKn2oH6wxOY88ifKZiSv676LnWEsSZqGInnxMVw9ohWbEdvxz8Q7jzK9+rzibb8ddsx58A8BxEu3xdeTsBscNU2u1t91yrAlEtNwXDovZ5vdIwHLY4m7IOUcaBkjt+Cps7mAER6pdMZ6LiaFhrDiG24xeVzsbgbIGp/b+C+o73XLtNAblcCahVrWdQbysnII6s2+p/kE0UtUNyDqIqXFLmqWjz9JtaQ1uB6IspBf0HcluYxiT0lWwW5VE/UKQhamNBf80Zz7Wa1TBjgeFQlwNwTb4+rfZ2K8qoH/Vm0GDkpPxCjeqdZvJU2QzEGYcyUBt1F/S2BztGs+ZKo1qF3lmaNXx2o2BQq+mN1t9Rf4XcJmqNJmvYvv3oE2lKljML0XxYk028IsTZlDLqAZFGhx2eO92wNis2kTvynDKpaJhNnXZG1jZClKrzNc+1qkETRRkAdQnii6afLUgpr5tV/xMtNDuqhmnNxjaUlden9fUrI0K7qap9xkQPPkNX266mgWByXMp1iKaZaZxFSnndsNM1LlhzCMtBHIETEGMB8urpK9vxy55rzaN+ZL8kA6Isf05DHP2CqnNw5IHt+BXPtdaCdQOoKoOkJhA+E2KqkainIcuy3buG+jn3kvJ+ThmmnZa/U8PmhCzbkjJPsP6KLFsWDUY8tkqealQ/oyQ/o4p6tb2jz2hBGfW/3euea83Jzw/6ntSa3nkl6AGxDdWaT8dnl3Y61hwUSlszkDN0TmYR7qiagjjSnEe9zwJynrRh2UBCWe40wm1x01E+h/AowLNy2aB8JcP7V+U8J7B1h18a4VGaZyFqOcEw8RXzYtui/l4nAFyEGEodfMa8aaEuyiJcKzsDsX3SQK0zUt1Gp1H/G6nh+uownNZkOGjkRTXqTlLU3g/OOFyAufq/Lt9L6+f75dHpFBrvpPMAjCMXlcvJjTuQ/LKmGqx7BVu0kWVZZ2AOgUV0oT9A7nyzMG+3OdvxZxq81xXyd0yjSQjJUZHN/raztuObmhyxMzS3iesV7bLjTi7ZNl7W3GDZUaD2Zd9q3S2XSVm+9jv1qke+lcvOe0luw9FmNYB2L8ePC4YDERmxWUFERgwHIjJiOBCREcOBiIwYDkRkxHAgIiOGAxEZMRyIyIjhQERGDAciMmI4EJERw4GIjBgORGTEcCAiI4YDERkxHIjIiOFAREYMByIyYjgQkRHDgYiMGA5EZMRwICIjhgMRGTEciMiI4UBERgwHIjJiOBCREcOBiIwYDkRkxHAgIiOGAxEZMRyIyIjhQERGDAciMmI4EJERw4GIjBgORGTEcCAiI4YDERkxHIjIiOFAREYMByIyYjgQkRHDgYiM/h9Kx75WJQpNUwAAAABJRU5ErkJggg=="
ICON_REST_PASSIV = "iVBORw0KGgoAAAANSUhEUgAAAQcAAACpCAYAAAAmyviNAAAACXBIWXMAABYlAAAWJQFJUiTwAAAR50lEQVR4nO3df2wb12EH8K+HYZEtZ5IBd0hyf4heWqQVgokyKgxwqujkrAjkQraKuYaKdBE15I8lWOdHJEDXqrXpP5S2wDCeZ2DB/mhEDdggpBlMW6iNDWhMhcswoEZMBoGGYE1NBWAaIEZDobWnpgGyP9478t3pkaLEH8cjvx9AgEjeHR+PvC/frzvu+/TTT0FE5Pd7QReAiDoTw4GIjBgORGTEcCAiI4YDERkxHIjIiOFAREYMByIyYjgQkRHDgYiMGA5EZMRwICIjhgMRGTEciMjo94MuAIXL1dVVB0B0F6vkABQAZE5OT+daUihqiX28ngPV6+rqagrAXAOb2ADgAEidnJ4uNaVQ1DIMB6rL1dXVCGQtYKAJm9sAEDs5PZ1pwraoRdjnQHU5OT1dAGAD2GzC5oYA3Li6uhprwraoRVhzoJZSNQ4bQAzAhGGR+ZPT06n2lYjqxXCgtrm6umoDSEHWHHSj7KzsPGxWUNuoPoYogLzvoVTbC0M7YjhQW6lRChvevosR9j90HoYDtZ0KCOG7eyaIslB17HPoQuOzCzOQ3867mazUDAUAGQDp7MrijvMYrq6uFqD1P5ycnt7XqoLR7jEcuogKBQfbO/zabROAk11ZTNRaSM22PKvdNcm5D52DzYou8cRfnP9XAJcRfDAAcqLU+T97+vx/j88uDNZYLuO7HWlZiWjXGA5d4MtziZc+/t0nXw+6HH6//fiTP93f9wev1FjE3/SItLA4tEs88SrkxmcXbAB/pd839NBhnH5yDGOPHmlrWQrFO/jnK/+J9XffL9/3f1sff3l8dkFkVxadthaGGsaaQ/gl9BsTY4/gh8+faXswAEDEOoxzz81gYuwR/0OJtheGGsZwCLHx2YUItCnJhw/dj6dPfSm4AinPzj6B4Ycf0u8aUJ2lFCJsVoSQOtCi8A1VWn90CNdffwtTj/8J+vffF0zhlKnHRzzNC8iypgMqDu0BwyFkxmcXYgCWTI/l33kP+Xfew8/evo1zz50KNCAMzRo7gGJQA9isCB//zMJtNt6/g+uvv9WOslAXYziEj43tJy55TIw9gtNPjrWnNNS12KwImezKYkkNX0Yhr5FQvmzb06ceQ8Q6jOGHrYBKR92ENYcQyq4slrIrixnIcxnKGAzUTKw5dJFf3916A8AnAAYBjARcHAo51hy6SHL5379rWZZtWVbUsqx9AEYBfBXARezQT0Hkx3DoYpZl5SzLSluWJSzLigI4BGAewDKac6HYhqgzMJfVzTzkGaXUIRgOPcSyrJJlWSnLsmKQJznNA1gLskwnp6djAOIAbP6WRWfh9RxCSJshacN7RedlyE5Kp56LrbiKxWL0jVv/+4O33nnvyQ9/9WsAwIH992Hs0SOYGPv8nss5+/w/6jfXsiuL9p43Rm3HDsmQqTVDEpVhzZnx2QXbHxDqXIwYZLAUIH+kJg1Znd922fibb9/GtdffwrOzx3Fv67dY//n7WH+3iOGHLQx/9iGOjHQ5hkP47DhDEnKkQkA7G3J8dsF/1SWXJ2j6D/QBAO7e2wIgZ1v+7d97L8mw/u77wH8AX3z0CJ6dPd7QNG3ttzcLAASbFp2D4RA+NuQVlGoNVS7rl2gbn11IwBwMZf0H+vD9F76B0WF5TsSt9dv4h+Wf4Ocbv6y6zs23b+OlldfwwvxUvWX3uLq6qpdrAnIIlmdvdgh2SIaMairYACZR6el3xQFMZlcWY+4d6jJt593b33z6K/jxpRcwf/p4uZbQf6APl849Uw4GABgdPoJL557BA4cHy8t8beoYfnzpBbz4/FPldW++fRuF4p29vhx7h9sUINYcQkgFREZNo9bl1MxJXXmZ+dPHcebEMQDAX55+AmemHkP25jpGh4/ggc8c2vY8B/v7sPTDb+La2ps4MXEUB/tlIDzwmUM4e28LL770bwBkQESsw3t5KRl4+zr8ZacAsebQ/crXfBgd/mPPAwf7+zA1cdQYDPoyZ04cKweDa2riaMMFOzk9nQBwAXI4dRmys5Q6BGsO3a/8G5S31n/haTr85u4Wrq29icfHvlA1INxl9JoDAFxfe7MphVMBQR2I4dD9Mu4/S6++hoMH9uPExFG8cv0NvHLtv3D33hZefvWnuHTuGXwu8qBnxd/c3cL8ty7hgzslvPzqT3HmxDGcmXoMt9Z/gYvLPykv98UArldJrcdJUCGk5itE4DtlG7JDMgfZ91DSlk9A65Q0eeDwIL7z3OlyzeKDDz/Ct//uX2qOVgAyGKqNVnASVLgxHEJmfHYhClkbGKixWB6A7QuIavMcPPoP9OH+A3344M7O0w3u7+/LON9+6mj//vv+0PQ4wyHc2CEZPmnUDgZAzoHwnMSUXVkUAP7Jvf21qWP4zrN/jus/+h6iWj/E3XtbnmD47NCDePkHf40Xn38K86eP65vMX/vR9yb799+3bWYldQf2OYTPDOqrOZhmUn7g/vM3c18p33np3DPI/mwd2Zv/g19++BEA4OCBPjw+Nlwelfhc5EGMjw1j6dXX3NVKgDzzs1gszqP6lG4KKYZDyGRXFnOqaRFBnX0O9RgfG8b42PCeymRZVqpYLEZRR7OFwoPhEELZlcUCgEKdk6DawrIsUSwWbfAKVF2DfQ7UTDF0wEVkqDkYDtQ0lmXlwKs5dQ2GAzWVZVkJ8HqVXYF9DiHkuxKULqb6IXZ1JagWEABuBPj81AQMh5Bp5EpQvu00u2hllmVlisXiGgxXl6LwYLMifOpp07tXgvJrZm1ip23FmvhcFADWHMLHxs6ToDxXgnJlVxYddV5GdNsau1PCDge/ZVmFBp+DAsZzK0JopxOvgprr4Dc+u6B/uHhuRciwWRFC2ZXFgum3MtFBwUDhx3AgIiOGAxEZMRyIyIjhQERGHMoMoTpmSKazK4s5/3pEu8GaQ8ioGZKXIa8J6Z+BOKfuz6hrPhDtGcMhfOr5rcwBcIYiNYjhED42dj7rcVldMzIwaqKWrhBAMagB7HMIGXUyVRQAVP+Cfvbjsv47mQGL+W6zDyRkWHMIMTUbUr/y0pzh0nFtp2oN/ppLOoCiUAMYDuHnP0szrUYzAlHldzXW1HUvKUTYrAg/B7IKP6RuDwC4PD67sAZ5kObQ3FO1TQYhmzpRAKd8j22CnaOhxLMyu0Cdv4IVlPnsymIq6ELQ7rFZ0QXUhCcbnXXtxk0AkwyG8GLNocuoSVIJVJoZ7bYBIIXgr2NJDWI4dCntgjDtVGDHY/dgOBCREfsciMiI4UBERgwHIjJiOBCREcOBiIwYDkRkxHAgIiOGAxEZMRyIyIjhQERGDAciMmI4EJERw4GIjBgORGTEcCAiI4YDERkxHIjIiOFAREYMByIyYjgQkRHDgYiMeubn8ERcxFDfpdrTTtLhL0JTz+uZS9OLuMgAmKhz8TwA20k6/FEW6lk9U3PYpREAGREXHRMQIi7cFF9zko4dZFnCStuHcJLOviDLEga9Gg6TTtLJ6HeIuBiE/L1JB/Kn5EYgf5w22uayEXUEdkgqTtIpOUknDRkQm+ruEREXM8GViig4vVpzqMpJOgXVP3FK3RUFkK62vKpxRNW6md08l4iLKIBBAKVWdIKKuIhAdcLutmztIuLCVv/uaR9orzHX7Cag/t62Yvudrlc7JLc1K3zLpgDMqZsXnKSTMCwTg/nXrNcAOKoWYtr2oFrvrO+hTcgmjaN/CPV2chWe16K2L9TfgKFswn8QirhIADivblZ7vTaAG+529H4P3/qTkIGXgGyamcoYVY+7AezahPyF7oT/QPQ9xyG1/gy8+7/a69tpH3pesypfSiu/K6+2n0EPYLPCTO9n8H/QBlXQLMH8M/cTAC6rgPFQB24G24MBkAfyeciO0MG9FFrb/nlsDwa3bBn14W+VBIDL2H5gASiH6i1sDwZAlvks5GuopaCW8+//CQCpve4/X/lM5R8BcEMt0/UYDj7qjdc/GAXfIil4h0TzAC4CWAawod0/J+JC+NZNaNveBHAFwAW1rmsE8lvfdUH9uTa0+y74ypf2lT2vlrmi3TeAGs2kJtD3zZr6KwHlJoCjPe7ug4vw7rsRw77TucG3jMr+K/cTYXu4+Pehft8Fd3kVKkvaMnntOfTyLanX0tV6tc8hKuLbPns2ZI1B/0a7qFdRVdVaf3zZSTox7fFByPBwl0mIuEhpVWS9czPhJB1HW9eBPGjdPwCAW90VceFWqQtVqv1ReA9Mf1XeRqVZMCTiIuIknYJ/O02SBzBj2H4MlQM77yQdvQYjfM25GXiDxG/U995EIb/xARkutvv6DfsQpn0I+RlwbcI71yUh4sJ9X9JQgdfNejUcknUsk4f8ptfpiXJFDwZAjngAmBFxUYI8CAYgP+QptYhe3S351s2hvhmcRk7SyYm4GFVlLPjbxU7SyYi4yKNSs4hge62oGTZhDgZAHuwFyH2SMDyeQCUcaln29yuo17+srW9j5+aJn/7+FPwPOkmnp0auejUcatmE71tdY2v/F7Sedr8CvAehK43Kh3dJDZNmAGSaMVqhthFzb2ujIRH1t+e2+C6kq9VIVHimUAlLfbTCLWtdz1Hl/hzqC5dqMtr/IwByqraQgXyPur62oOvVcIjD29GYRqW6K5ykk6qynt7JdxbmjsVaBORB4AbHKfUHERcbkN+c6UY+hCpwYjB3+LVDzZDTRlNiMHfo1qPa/mkoYNUw9jwq/Q5D0N5nVTNJcbSiu+WcpJNx/+Bt2zqN9HbXog56GzKc8r6HhyA/lI2MVqQgRwqCCgagxgGqOvFykKMppmDYNNzXVuqLYRTeTk7XHDha0VtU55TbGz0Ac3sY8H5YLkCO6e/0l/I9V8lJOo7qjDsCYB6yR9814l+nHuoDq1ep82rbkwAOqXMJ/IHUbilUQmET8gD8KmTn4j54m22BcZJOzkk6MSfpDELuv4vwvvdLLR4O7gi92qwwiaHSm39WjTL4vwUzqHwrR6pVL91vflPzwO0HULWWAlQbXA3duR2ldo1yRmqU3+UZRdEY5x7AW02vtv1q99dF7RN9NGXGsP8CP+BUOWfcpqUqY0ZNwsqgsg9tNNiM6XSsOSjqQ6DPBzB1SOodYXOm6qU2EekjERdpdzxcxEVUxEUBcrgtZdh2vR+0oTq+tQqGcpme0/TcM/4xfG1WZyP8TaWC4TlqzW1oKlNnsgqAjyBrBjH9MRX0eoi2o3M3UKw5eAlUagYTIi6EPmrhJJ2U+tC434BL6kOWUbej8E7pjUJ9oNRQm/uBGhJxkUNlaM+G98Aw9cbrw5Bp9UEuQfafFFQZ3HLFVBAVID/EMdToh1DDnBuq3AOofFMWIGsMAnvvPHSfo6A9ByD7dlKovP4YqtdsmuUKKvshpeaWFCDP68jAe/C7720Kch/Y8NZ8WjmRrCOw5qBRB5k+ky5h6BycgbftPgfZkbgE75Red7xf/8DpATCi1rkB73Rn9/wCv5j2v9t5eRmV6n4KlXax+/gNeDso9Vl+fjNV1l9SZW1GZ6F+QJ1SZbsF2ZwaQev7RBLwvsakKoMNAOqLwP/euvtA78+50gtXC2M4bOfA2znpaV5oIw7LqG4ZQNQwUScF2QFX7UDLq/Uy2woltzWPKge4Cja7yrY31fOmqhVYbb/a+nk0obPQSToCcqTGxH2Olo1YaK+xVkjaqP3eXuiVyVC91KwQqLQTq6a+k3RKqjoZqbUMZNVdoDLt2t2uW82vtm4awKB6DnfiTwl1TIRS4ZLSJjd5Xota37/tjCpTSTVlMv719PVVf0NUva6CWjcHACIuJtWi/o7WVK3t+p7DUROLoqg0u3JuIKqyu/tkt8+RgxxdAKrM/nRnouqns+vLau9tQiuju+2emgjVM6dsE9HusFlBREYMByIyYjgQkRHDgYiMGA5EZMRwICIjhgMRGTEciMiI4UBERgwHIjJiOBCREcOBiIwYDkRkxHAgIiOGAxEZMRyIyIjhQERGDAciMmI4EJERw4GIjBgORGTEcCAiI4YDERkxHIjIiOFAREYMByIyYjgQkRHDgYiMGA5EZMRwICIjhgMRGTEciMiI4UBERgwHIjJiOBCREcOBiIwYDkRkxHAgIiOGAxEZMRyIyIjhQERGDAciMmI4EJERw4GIjP4fBp/p1UM9wk8AAAAASUVORK5CYII="
ICON_HAKEN         = "PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyMC42MSAxNi4zOSI+PHBhdGggZD0iTTcuMTYsMTUuODloMGMtLjY1LDAtMS4yNy0uMjYtMS43My0uNzJMMS4yMiwxMC45NWMtLjk2LS45NS0uOTYtMi41LDAtMy40Ni45Ni0uOTUsMi41LS45NSwzLjQ2LDBsMi40OSwyLjQ5TDE1LjkzLDEuMjJjLjk2LS45NiwyLjUtLjk2LDMuNDYsMCwuOTYuOTUuOTYsMi41LDAsMy40NmwtMTAuNSwxMC41Yy0uNDYuNDYtMS4wOC43Mi0xLjczLjcyWiIgc3R5bGU9ImZpbGw6bm9uZTtzdHJva2U6IzliOTI4YjtzdHJva2UtbWl0ZXJsaW1pdDoxMCIvPjwvc3ZnPg=="
ICON_FAV_PASSIV    = "PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxNy44NSAxNi40NiI+PHBhdGggZD0iTTguOTIsMTUuOTZDNS40NCwxMy4xNy41LDguMy41LDQuNDQuNSwyLjIxLDIuNC41LDQuNzUuNWMyLjAzLDAsMy40NiwxLjA1LDQuMTcsMy42My43Mi0yLjU4LDIuMTItMy42Myw0LjE3LTMuNjMsMi4zNSwwLDQuMjUsMS43MSw0LjI1LDMuOTQsMCwzLjg2LTQuOTQsOC43My04LjQyLDExLjUyWiIgc3R5bGU9ImZpbGw6bm9uZTtzdHJva2U6IzliOTI4YjtzdHJva2UtbGluZWNhcDpyb3VuZDtzdHJva2UtbGluZWpvaW46cm91bmQiLz48L3N2Zz4="

def svg_img(b64, width="100%"):
    return f'<img src="data:image/svg+xml;base64,{b64}" width="{width}" style="display:block"/>'

# ─────────────────────────────────────────────
# CSS
# ─────────────────────────────────────────────
st.markdown("""
<style>
@import url('https://fonts.googleapis.com/css2?family=Albert+Sans:wght@300;400;500;600;700&display=swap');

/* ── Hide Streamlit chrome (inkl. bottom-right Badge) ── */
#MainMenu, header[data-testid="stHeader"], [data-testid="stToolbar"],
footer, .viewerBadge_container__1QSob, [data-testid="stDecoration"],
.stDeployButton, [data-testid="manage-app-button"],
[data-testid="stStatusWidget"],
[data-testid="stAppViewBlockContainer"] ~ div,
.st-emotion-cache-1dp5vir, .st-emotion-cache-eczf2e,
[class*="StatusWidget"], [class*="toolbarActions"] {
    display: none !important;
    visibility: hidden !important;
    height: 0 !important;
    pointer-events: none !important;
}

/* ── Basis ── */
html, body, [class*="css"] {
    font-family: 'Albert Sans', sans-serif !important;
    background: #fff;
    -webkit-text-size-adjust: 100%;
}
/* FIX iOS Rubber Banding: verhindert das elastische Überscollen des gesamten Screens */
html, body {
    overscroll-behavior: none !important;
    overscroll-behavior-y: none !important;
    -webkit-overflow-scrolling: auto !important;
    height: 100% !important;
}
/* FIX Nav-Bar: overflow:visible auf Root-Elementen damit position:fixed
   relativ zum Viewport funktioniert (iOS Safari-Bug mit overflow:hidden) */
.stApp {
    background: #fff !important;
    overflow: visible !important;
    transform: none !important;
    overscroll-behavior: none !important;
}
[data-testid="stAppViewContainer"] {
    overflow-x: hidden !important;
    overflow-y: auto !important;
    transform: none !important;
    overscroll-behavior: none !important;
}
[data-testid="stMain"], [data-testid="stVerticalBlock"] {
    transform: none !important;
    filter: none !important;
}
/* FIX Hochformat-Sperre: bei Querformat Hinweis anzeigen */
@media screen and (orientation: landscape) and (max-height: 500px) {
    body::after {
        content: '';
        position: fixed; top: 0; left: 0; right: 0; bottom: 0;
        background: #fff; z-index: 99999;
    }
    body::before {
        content: 'Bitte drehe dein Gerät in den Hochformat-Modus';
        position: fixed; top: 50%; left: 50%; transform: translate(-50%, -50%);
        font-family: 'Albert Sans', sans-serif;
        font-size: 17px; font-weight: 500; color: #000;
        text-align: center; padding: 0 32px; z-index: 100000;
        line-height: 1.5;
    }
}
.block-container {
    padding: 16px 16px 100px 16px !important;
    max-width: 430px !important;
    margin: 0 auto !important;
}

/* ── Typografie ── */
h1 {
    font-family: 'Albert Sans', sans-serif !important;
    font-size: 26px !important; font-weight: 700 !important;
    color: #b78715 !important; margin-bottom: 4px !important;
}
h2 {
    font-family: 'Albert Sans', sans-serif !important;
    font-size: 16px !important; font-weight: 600 !important;
    color: #9b928b !important; margin: 14px 0 4px !important;
}
p, .stMarkdown p {
    font-family: 'Albert Sans', sans-serif !important;
    color: #000 !important; font-size: 15px !important;
}
label { font-family: 'Albert Sans', sans-serif !important; color: #000 !important; }

/* ── Buttons allgemein ── */
.stButton > button {
    font-family: 'Albert Sans', sans-serif !important;
    border-radius: 12px !important; cursor: pointer !important;
    transition: opacity 0.2s !important;
}
.stButton > button[kind="primary"] {
    background: #b78715 !important; color: #fff !important;
    border: none !important; font-weight: 700 !important;
    font-size: 16px !important; padding: 14px 24px !important; width: 100% !important;
}
/* FIX: Neuere Streamlit-Versionen rendern Button-Text in einem inneren <p> –
   dieser braucht eigene Farb- und Gewicht-Regeln */
.stButton > button[kind="primary"] p,
.stButton > button[kind="primary"] div {
    color: #fff !important;
    font-weight: 700 !important;
}
.stButton > button[kind="primary"]:hover { opacity: 0.88 !important; }
.stButton > button[kind="primary"]:disabled {
    background: #e0d5c0 !important; color: #a0906a !important;
}
.stButton > button[kind="secondary"] {
    background: transparent !important; color: #3c577a !important;
    border: 1.5px solid #3c577a !important; font-weight: 500 !important;
    font-size: 15px !important; padding: 10px 20px !important; width: 100% !important;
}
.stButton > button:not([kind]) {
    background: transparent !important; border: none !important;
    color: #3c577a !important; font-weight: 500 !important;
    padding: 4px 0 !important; box-shadow: none !important;
}

/* ── Inputs ── */
.stTextInput > div > div > input, .stTextArea textarea, .stNumberInput input {
    font-family: 'Albert Sans', sans-serif !important;
    border: 1.5px solid #e0e0e0 !important; border-radius: 10px !important;
    padding: 12px 14px !important; font-size: 15px !important;
    color: #000 !important; background: #f9f9f9 !important;
}
.stTextInput > div > div > input:focus, .stTextArea textarea:focus {
    border-color: #b78715 !important;
    box-shadow: 0 0 0 2px rgba(183,135,21,0.15) !important;
}
.stTextInput label, .stTextArea label, .stNumberInput label {
    color: #9b928b !important; font-size: 13px !important; font-weight: 500 !important;
}

/* ── Checkbox ── */
.stCheckbox input[type="checkbox"] { accent-color: #b78715 !important; width: 18px !important; height: 18px !important; }
.stCheckbox label span { color: #000 !important; font-size: 14px !important; }

/* ── Radio ── */
.stRadio label { color: #000 !important; font-size: 15px !important; }
.stRadio input[type="radio"]:checked { accent-color: #b78715 !important; }

/* ── Tabs – kein beweglicher Unterstrich ── */
.stTabs [data-baseweb="tab-list"] {
    background: transparent !important;
    border-bottom: 1.5px solid #f0f0f0 !important; gap: 0 !important;
}
.stTabs [data-baseweb="tab"] {
    font-family: 'Albert Sans', sans-serif !important;
    font-weight: 500 !important; font-size: 15px !important;
    color: #9b928b !important;
    border-bottom: 2px solid transparent !important;
    padding: 12px 24px !important; flex: 1 !important;
    justify-content: center !important;
    transition: none !important;
}
.stTabs [aria-selected="true"] {
    color: #b78715 !important;
    border-bottom: 2px solid #b78715 !important;
    background: transparent !important;
}
.stTabs [data-baseweb="tab-highlight"] { display: none !important; }
.stTabs [data-baseweb="tab-border"] { display: none !important; }

/* ── Alerts / Captions / HR ── */
.stAlert { border-radius: 12px !important; font-family: 'Albert Sans', sans-serif !important; }
.stCaption { color: #9b928b !important; font-size: 13px !important; }
hr { border: none !important; border-top: 1px solid #f0f0f0 !important; margin: 10px 0 !important; }

/* ── File-Uploader (Scan-Seite) ── */
[data-testid="stFileUploaderDropzone"] {
    display: none !important;
}
[data-testid="stFileUploaderDropzoneInstructions"] {
    display: none !important;
}
section[data-testid="stFileUploader"] label {
    display: none !important;
}
section[data-testid="stFileUploader"] > div > button,
section[data-testid="stFileUploader"] button[kind="secondary"] {
    background: #b78715 !important; color: #fff !important;
    border: none !important; border-radius: 12px !important;
    font-weight: 700 !important; font-size: 16px !important;
    width: 100% !important; padding: 14px 24px !important;
}
section[data-testid="stFileUploader"] button[kind="secondary"] p {
    color: #fff !important; font-weight: 700 !important;
}

/* ── Bottom Nav (reines HTML-Element) ── */
.nc-bottom-nav {
    position: fixed; bottom: 0; left: 50%; transform: translateX(-50%);
    width: 100%; max-width: 430px; height: 72px;
    background: #fff; border-top: 1px solid #f0f0f0;
    z-index: 9999; box-shadow: 0 -2px 12px rgba(0,0,0,0.07);
    display: flex; align-items: center;
}
.nc-bottom-nav a {
    flex: 1; display: flex; align-items: center; justify-content: center;
    height: 100%; text-decoration: none; -webkit-tap-highlight-color: transparent;
}
.nc-bottom-nav a img { height: 68px; width: auto; display: block; }

/* ── Profil Listenzeilen (reines HTML) ── */
.profil-section-title {
    font-size: 13px; font-weight: 600; color: #9b928b;
    text-transform: uppercase; letter-spacing: 0.5px;
    font-family: 'Albert Sans', sans-serif;
    margin: 20px 0 0; padding-bottom: 2px;
}
a.profil-row {
    display: flex; align-items: center; justify-content: space-between;
    padding: 16px 4px; border-bottom: 1px solid #f0f0f0;
    text-decoration: none; color: inherit; cursor: pointer;
    -webkit-tap-highlight-color: transparent;
}
a.profil-row:active { background: #f9f9f9; }
div.profil-row {
    display: flex; align-items: center; justify-content: space-between;
    padding: 16px 4px; border-bottom: 1px solid #f0f0f0; color: #9b928b;
}
.profil-row-label { font-size: 16px; color: #000; font-weight: 400; font-family: 'Albert Sans', sans-serif; }
.profil-row-right { display: flex; align-items: center; gap: 8px; }
.profil-row-value { font-size: 14px; color: #9b928b; font-family: 'Albert Sans', sans-serif; }
.profil-row-arrow { font-size: 18px; color: #9b928b; font-weight: 300; }

/* ── Upgrade Tabelle ── */
.upgrade-table {
    width: 100%; border-collapse: collapse;
    font-family: 'Albert Sans', sans-serif; font-size: 15px; margin: 8px 0;
}
.upgrade-table th {
    text-align: left; padding: 10px 8px; font-weight: 600;
    color: #9b928b; border-bottom: 1.5px solid #f0f0f0;
    border-left: none !important; border-right: none !important;
}
.upgrade-table th.plan { text-align: center; width: 70px; }
.upgrade-table th.plus { color: #b78715; }
.upgrade-table td {
    padding: 14px 8px; border-bottom: 1px solid #f5f5f5;
    color: #000; border-left: none !important; border-right: none !important;
}
.upgrade-table td.center { text-align: center; color: #9b928b; }
.upgrade-table td.ja { text-align: center; color: #b78715; }

/* ── Gericht Card ── */
.gericht-card {
    background: #f9f9f9; border-radius: 14px; padding: 14px 16px;
    margin-bottom: 10px; border: 1px solid #f0f0f0;
}
.gericht-nr { font-size: 12px; color: #9b928b; margin-bottom: 2px; }
.gericht-name { font-size: 16px; font-weight: 600; color: #000; }
.gericht-preis { font-size: 14px; color: #b78715; font-weight: 500; margin-top: 4px; }
.ampel-sicher { color: #2e7d32; font-size: 13px; font-weight: 500; }
.ampel-warnung { color: #c0392b; font-size: 13px; font-weight: 500; }

/* ── Disclaimer Box ── */
.disclaimer-box {
    background: #f9f9f9; border-radius: 14px; padding: 20px; margin: 16px 0;
    font-family: 'Albert Sans', sans-serif; font-size: 14px;
    line-height: 1.7; color: #000;
}

/* ── Scan Limit ── */
.scan-limit-box {
    background: #fffbf0; border: 1.5px solid #b78715; border-radius: 16px;
    padding: 24px; text-align: center; margin: 24px 0;
    font-family: 'Albert Sans', sans-serif;
}
</style>
""", unsafe_allow_html=True)

# ─────────────────────────────────────────────
# SUPABASE
# ─────────────────────────────────────────────
@st.cache_resource
def init_supabase() -> Client:
    return create_client(st.secrets["SUPABASE_URL"], st.secrets["SUPABASE_KEY"])

supabase = init_supabase()

# ── JS: Streamlit-Badge via DOM entfernen (CSS allein nicht zuverlässig) ──
components.html("""
<script>
(function() {
    function removeBadge() {
        var doc = window.parent.document;
        var selectors = [
            '[data-testid="stStatusWidget"]',
            '[data-testid="stToolbar"]',
            '[class*="StatusWidget"]',
            '[class*="toolbarActions"]',
            '[class*="stBottom"]',
            '.st-emotion-cache-zq5wmm',
            '.st-emotion-cache-1dp5vir',
            '.st-emotion-cache-h5rgaw'
        ];
        selectors.forEach(function(sel) {
            doc.querySelectorAll(sel).forEach(function(el) {
                el.style.setProperty('display', 'none', 'important');
            });
        });
        // Generisch: fixed-positionierte Elemente in bottom-right Ecke
        doc.querySelectorAll('body > div, .stApp > div').forEach(function(el) {
            var s = window.getComputedStyle(el);
            if (s.position === 'fixed' && parseInt(s.bottom) < 100 &&
                parseInt(s.right) < 100 && el.offsetWidth < 300) {
                // nur kleine Elemente unten rechts (= Badge), nicht Nav-Bar
                if (el.offsetWidth < 200 && el.offsetHeight < 80) {
                    el.style.setProperty('display', 'none', 'important');
                }
            }
        });
    }
    // Mehrfach versuchen, da Streamlit asynchron rendert
    [300, 800, 1500, 3000].forEach(function(ms) {
        setTimeout(removeBadge, ms);
    });
})();
</script>
""", height=0)

# ─────────────────────────────────────────────
# KONFIGURATION
# ─────────────────────────────────────────────
ALLERGEN_LABELS = {
    "A": "Glutenhaltiges Getreide (Weizen, Roggen, Gerste, Hafer, Dinkel ...)",
    "B": "Krebstiere", "C": "Eier", "D": "Fische", "E": "Erdnüsse",
    "F": "Soja", "G": "Milch (Kuh, Schaf, Ziege, Pferd, Esel und Erzeugnisse)",
    "H": "Schalenfrüchte (Mandeln, Haselnüsse, Walnüsse, Cashews ...)",
    "L": "Sellerie", "M": "Senf", "N": "Sesam",
    "O": "Schwefeldioxid und Sulfite (> 10 mg/kg oder 10 mg/l)",
    "P": "Lupinen", "R": "Weichtiere"
}
ALLERGEN_SHORT = {
    "A": "Gluten", "B": "Krebstiere", "C": "Eier", "D": "Fische",
    "E": "Erdnüsse", "F": "Soja", "G": "Milch", "H": "Schalenfrüchte",
    "L": "Sellerie", "M": "Senf", "N": "Sesam", "O": "Sulfite",
    "P": "Lupinen", "R": "Weichtiere"
}
FREEMIUM_SCAN_LIMIT = 3

# Welche Seite setzt welchen aktiven Tab
PAGE_TO_TAB = {
    "scan": "scan",
    "restaurants": "restaurants", "speisekarte": "restaurants",
    "profil_uebersicht": "profil", "allergen_settings": "profil",
    "upgrade": "profil", "auth": "profil", "alternatives": "scan",
}

# ─────────────────────────────────────────────
# SESSION STATE
# ─────────────────────────────────────────────
for k, v in {
    "page": "disclaimer",
    "user": None, "profile": None,
    "user_allergene": [],
    "disclaimer_accepted": False,
    "onboarding_complete": False,
    "restaurant_logged_in": False,
    "restaurant_data": None,
    "active_tab": "scan",
    "local_scan_count": 0,
}.items():
    if k not in st.session_state:
        st.session_state[k] = v

# ─────────────────────────────────────────────
# QUERY-PARAM NAVIGATION
# Ermöglicht Navigation via reiner HTML <a href="?page=...">-Links.
# Streamlit erkennt Query-Param-Änderungen und löst einen Rerun aus.
# ─────────────────────────────────────────────
_qp_page = st.query_params.get("page", "")
if _qp_page:
    st.query_params.clear()
    st.session_state.page = _qp_page
    if _qp_page in PAGE_TO_TAB:
        st.session_state.active_tab = PAGE_TO_TAB[_qp_page]
    st.rerun()

def navigate(page):
    st.session_state.page = page
    if page in PAGE_TO_TAB:
        st.session_state.active_tab = PAGE_TO_TAB[page]
    st.rerun()

# ─────────────────────────────────────────────
# HILFSFUNKTIONEN
# ─────────────────────────────────────────────
def load_profile(user_id):
    res = supabase.table("user_profiles").select("*").eq("id", user_id).single().execute()
    if res.data:
        p = res.data
        st.session_state.profile = p
        if not st.session_state.disclaimer_accepted:
            st.session_state.disclaimer_accepted = p.get("disclaimer_accepted", False)
        st.session_state.user_allergene = [k for k in ALLERGEN_LABELS if p.get(k, False)]

def save_allergene(selected):
    st.session_state.user_allergene = selected
    if not st.session_state.user:
        return
    upd = {k: (k in selected) for k in ALLERGEN_LABELS}
    supabase.table("user_profiles").update(upd).eq("id", st.session_state.user.id).execute()

def save_disclaimer():
    st.session_state.disclaimer_accepted = True
    if not st.session_state.user:
        return
    from datetime import datetime, timezone
    supabase.table("user_profiles").update({
        "disclaimer_accepted": True,
        "disclaimer_accepted_at": datetime.now(timezone.utc).isoformat()
    }).eq("id", st.session_state.user.id).execute()

def get_scan_count():
    if not st.session_state.user:
        return st.session_state.local_scan_count
    res = supabase.table("scan_log").select("id", count="exact").eq("user_id", st.session_state.user.id).execute()
    return res.count or 0

def log_scan(scan_type):
    if not st.session_state.user:
        st.session_state.local_scan_count += 1
    else:
        supabase.table("scan_log").insert({"user_id": st.session_state.user.id, "scan_type": scan_type}).execute()

def is_premium():
    return st.session_state.profile and st.session_state.profile.get("plan") == "premium"

def check_ampel(gericht, allergene):
    for a in allergene:
        if gericht.get(a):
            return False, ALLERGEN_SHORT[a]
    return True, ""

# ─────────────────────────────────────────────
# BOTTOM NAVIGATION — reines HTML, kein Streamlit-Button-Trick
# Icons direkt als <img> eingebettet, Links via ?page= Query-Param
# ─────────────────────────────────────────────
def bottom_nav():
    tab = st.session_state.active_tab
    p_icon = ICON_PROFIL_AKTIV if tab == "profil"      else ICON_PROFIL_PASSIV
    s_icon = ICON_SCAN_AKTIV   if tab == "scan"        else ICON_SCAN_PASSIV
    r_icon = ICON_REST_AKTIV   if tab == "restaurants" else ICON_REST_PASSIV

    # FIX: target="_self" verhindert, dass Links in neuem Tab öffnen
    st.markdown(f"""
    <div class="nc-bottom-nav">
        <a href="?page=profil_uebersicht" target="_self">
            <img src="data:image/png;base64,{p_icon}" />
        </a>
        <a href="?page=scan" target="_self">
            <img src="data:image/png;base64,{s_icon}" />
        </a>
        <a href="?page=restaurants" target="_self">
            <img src="data:image/png;base64,{r_icon}" />
        </a>
    </div>
    """, unsafe_allow_html=True)

# ─────────────────────────────────────────────
# SEITE 1: DISCLAIMER
# ─────────────────────────────────────────────
def page_disclaimer():
    st.markdown("# 🥜 Nuss-Checker")
    st.markdown("---")
    st.markdown("## Wichtiger Hinweis")
    st.markdown("""
    <div class="disclaimer-box">
    <strong>Diese App dient ausschließlich als Hilfestellung.</strong><br><br>
    Der Nuss-Checker kann keine Garantie für die Richtigkeit, Vollständigkeit
    oder Aktualität der angezeigten Allergeninformationen übernehmen.
    Die Angaben basieren auf Daten Dritter (Restaurants, Hersteller, Open Food DB)
    und können fehlerhaft oder veraltet sein.<br><br>
    Bei schweren Allergien oder Unverträglichkeiten wende dich bitte immer
    direkt an das Restaurant oder den Hersteller und konsultiere im Zweifelsfall einen Arzt.<br><br>
    <strong>Die Nutzung der App erfolgt auf eigene Verantwortung.</strong>
    </div>
    """, unsafe_allow_html=True)

    accepted = st.checkbox("Ich habe den Hinweis gelesen und akzeptiere, dass diese App keine Haftung übernimmt.")

    def start():
        save_disclaimer()
        navigate("allergen_settings")

    st.button("App starten →", on_click=start, type="primary", disabled=not accepted)

# ─────────────────────────────────────────────
# SEITE 2: ALLERGEN-EINSTELLUNGEN
# ─────────────────────────────────────────────
def page_allergen_settings():
    is_onboarding = not st.session_state.onboarding_complete

    if not is_onboarding:
        if st.button("← Zurück"):
            navigate("profil_uebersicht")

    st.markdown("# Meine Allergene")
    st.markdown('<p style="color:#9b928b;font-size:14px;margin-bottom:8px">Welche Allergene soll die App für dich hervorheben?</p>', unsafe_allow_html=True)

    selected = []
    for key, label in ALLERGEN_LABELS.items():
        checked = st.checkbox(f"**{key}** – {label}", value=(key in st.session_state.user_allergene), key=f"al_{key}")
        if checked:
            selected.append(key)

    st.markdown("---")

    def save_and_go():
        save_allergene(selected)
        st.session_state.onboarding_complete = True
        navigate("scan")

    btn = "Speichern und weiter →" if is_onboarding else "Speichern"
    st.button(btn, on_click=save_and_go, type="primary")

    if not is_onboarding:
        bottom_nav()

# ─────────────────────────────────────────────
# SEITE 3: AUTH
# ─────────────────────────────────────────────
def page_auth():
    tab_reg, tab_login = st.tabs(["Registrieren", "Einloggen"])

    with tab_reg:
        st.markdown("## Neues Konto")
        reg_type = st.radio("", ["Ich bin Endkunde", "Ich registriere mich als Restaurant"],
                            label_visibility="collapsed", key="reg_type")
        email_r = st.text_input("E-Mail-Adresse", key="reg_email")
        pw_r    = st.text_input("Passwort (mindestens 6 Zeichen)", type="password", key="reg_pw")
        pw_r2   = st.text_input("Passwort wiederholen", type="password", key="reg_pw2")

        is_restaurant = "Restaurant" in reg_type
        rest_name = rest_land = rest_plz = rest_adresse = rest_hnr = ""
        if is_restaurant:
            rest_name    = st.text_input("Restaurantname", key="rn")
            rest_land    = st.text_input("Land", key="rl")
            rest_plz     = st.text_input("Postleitzahl", key="rp")
            rest_adresse = st.text_input("Adresse", key="ra")
            rest_hnr     = st.text_input("Hausnummer", key="rh")

        all_ok = bool(email_r and pw_r and pw_r2)
        if is_restaurant:
            all_ok = all_ok and bool(rest_name and rest_land)

        btn_lbl = "Registrieren" if is_restaurant else "Für 2,99 €/Monat registrieren"
        # (kein Pfeil im Label)

        def do_register():
            if pw_r != pw_r2:
                st.error("Passwörter stimmen nicht überein.")
                return
            if len(pw_r) < 6:
                st.error("Passwort muss mindestens 6 Zeichen haben.")
                return
            try:
                res = supabase.auth.sign_up({"email": email_r, "password": pw_r})
                st.session_state.user = res.user
                load_profile(res.user.id)
                if is_restaurant:
                    supabase.table("restaurants").insert({
                        "owner_id": res.user.id, "name": rest_name,
                        "adresse": f"{rest_adresse} {rest_hnr}, {rest_plz} {rest_land}"
                    }).execute()
                navigate("scan" if st.session_state.disclaimer_accepted else "disclaimer")
            except Exception as e:
                st.error(f"Registrierung fehlgeschlagen: {e}")

        st.button(btn_lbl, on_click=do_register, type="primary", use_container_width=True, disabled=not all_ok)
        st.caption("Nach der Registrierung bitte E-Mail bestätigen.")

    with tab_login:
        st.markdown("## Anmelden")
        email_l = st.text_input("E-Mail-Adresse", key="login_email")
        pw_l    = st.text_input("Passwort", type="password", key="login_pw")
        st.markdown('<p style="color:#3c577a;font-size:13px">Passwort vergessen?</p>', unsafe_allow_html=True)

        def do_login():
            try:
                res = supabase.auth.sign_in_with_password({"email": email_l, "password": pw_l})
                st.session_state.user = res.user
                load_profile(res.user.id)
                navigate("scan" if st.session_state.disclaimer_accepted else "disclaimer")
            except Exception as e:
                st.error(f"Login fehlgeschlagen: {e}")

        st.button("Einloggen", on_click=do_login, type="primary", use_container_width=True)

    bottom_nav()

# ─────────────────────────────────────────────
# SEITE 4: SCAN
# ─────────────────────────────────────────────
def page_scan():
    scan_count = get_scan_count()

    if not is_premium() and scan_count >= FREEMIUM_SCAN_LIMIT:
        st.markdown(f"""
        <div class="scan-limit-box">
            <p style="font-size:16px;color:#000;line-height:1.6;margin-bottom:20px">
                Du hast heute schon<br>
                <strong>{FREEMIUM_SCAN_LIMIT}-mal geprüft.</strong><br>
                Unterstütze uns, um unbegrenzt zu scannen!
            </p>
        </div>
        """, unsafe_allow_html=True)
        st.button("Upgrade für 2,99 €/Monat", type="primary", use_container_width=True, on_click=lambda: navigate("upgrade"))
        bottom_nav()
        return

    if not is_premium():
        st.caption(f"Noch {FREEMIUM_SCAN_LIMIT - scan_count} von {FREEMIUM_SCAN_LIMIT} heutigen Scans")

    scan_mode = st.radio("", [
        "🛒 Produktetikett",
        "🌍 Fremdsprachiges Etikett",
        "📋 Restaurant QR-Code"
    ], label_visibility="collapsed", horizontal=True)

    st.markdown("""
    <div style="background:#f9f9f9;border:1.5px dashed #e0e0e0;border-radius:14px;
    padding:24px 16px;text-align:center;margin:12px 0;">
        <p style="font-size:28px;margin:0">📷</p>
        <p style="font-size:15px;color:#9b928b;margin:6px 0 0">
            Foto aufnehmen oder aus Galerie wählen
        </p>
    </div>
    """, unsafe_allow_html=True)
    camera_image = st.file_uploader(
        "", type=["jpg", "jpeg", "png", "webp"],
        label_visibility="collapsed", key="scan_upload"
    )

    if camera_image:
        st.markdown("---")
        if "Produktetikett" in scan_mode:
            log_scan("produkt")
            st.markdown("#### 🔍 Erkannte Allergene")
            st.info("⚙️ Texterkennung folgt in Phase 2 (OCR)")
            for a in st.session_state.user_allergene:
                st.markdown(f'<p class="ampel-warnung">⚠️ Enthält: {ALLERGEN_SHORT[a]}</p>', unsafe_allow_html=True)
            if st.session_state.user_allergene:
                st.button("🔄 Sichere Alternativen", type="primary", on_click=lambda: navigate("alternatives"))
        elif "Fremdsprachig" in scan_mode:
            log_scan("fremdsprache")
            st.info("⚙️ Übersetzungs-API folgt in Phase 2")
            for a in st.session_state.user_allergene:
                st.markdown(f'<p class="ampel-warnung">⚠️ Enthält: {ALLERGEN_SHORT[a]}</p>', unsafe_allow_html=True)
        else:
            log_scan("qr_code")
            st.info("⚙️ QR-Decode folgt in Phase 2")
            st.button("🍽️ Speisekarte öffnen", type="primary", on_click=lambda: navigate("restaurants"))

    bottom_nav()

# ─────────────────────────────────────────────
# SEITE 5: RESTAURANTS
# ─────────────────────────────────────────────
def page_restaurants():
    tab_karte, tab_liste, tab_lesezeichen = st.tabs(["Karte", "Liste", "Lesezeichen"])

    with tab_karte:
        st.info("⚙️ Kartenansicht folgt in Phase 2 (Google Maps / Mapbox)")

    with tab_liste:
        try:
            res = supabase.table("restaurants").select("id, name, adresse").eq("aktiv", True).execute()
            restaurants = res.data or []
        except:
            restaurants = []

        if not restaurants:
            st.markdown('<p style="color:#9b928b">Noch keine Restaurants eingetragen.</p>', unsafe_allow_html=True)
        else:
            for r in restaurants:
                col1, col2 = st.columns([8, 1])
                with col1:
                    if st.button(f"**{r['name']}**  \n{r.get('adresse','')}", key=f"r_{r['id']}"):
                        st.session_state["sel_rest_id"] = r["id"]
                        st.session_state["sel_rest_name"] = r["name"]
                        navigate("speisekarte")
                with col2:
                    st.markdown(svg_img(ICON_FAV_PASSIV, "24px"), unsafe_allow_html=True)
                st.markdown("<hr style='margin:4px 0'>", unsafe_allow_html=True)

    with tab_lesezeichen:
        if not is_premium():
            st.markdown('<div class="disclaimer-box" style="text-align:center"><strong>Plus-Feature</strong><br>Lesezeichen sind im Plus-Tarif verfügbar.</div>', unsafe_allow_html=True)
            st.button("Upgrade für 2,99 €/Monat", type="primary", use_container_width=True, on_click=lambda: navigate("upgrade"))
        else:
            st.info("Deine gespeicherten Restaurants erscheinen hier.")

    bottom_nav()

# ─────────────────────────────────────────────
# SEITE 6: SPEISEKARTE
# ─────────────────────────────────────────────
def page_speisekarte():
    rest_name = st.session_state.get("sel_rest_name", "Speisekarte")
    rest_id   = st.session_state.get("sel_rest_id")
    st.markdown(f"# {rest_name}")
    if st.session_state.user_allergene:
        st.caption("Gefiltert nach: " + " · ".join([ALLERGEN_SHORT[a] for a in st.session_state.user_allergene]))
    st.markdown("---")

    try:
        q = supabase.table("gerichte").select("*").eq("aktiv", True)
        if rest_id:
            q = q.eq("restaurant_id", rest_id)
        gerichte = q.execute().data or []
    except Exception as e:
        st.error(f"Fehler: {e}")
        gerichte = []

    for g in gerichte:
        sicher, warnung = check_ampel(g, st.session_state.user_allergene)
        if st.session_state.user_allergene and not sicher:
            continue
        preis = f"{g.get('preis','–')} €" if g.get("preis") else "–"
        ampel = '<span class="ampel-sicher">✓ Verträglich</span>' if sicher else f'<span class="ampel-warnung">⚠️ Enthält {warnung}</span>'
        st.markdown(f"""
        <div class="gericht-card">
            <div class="gericht-nr">Nr. {g.get('gericht_nummer','–')}</div>
            <div class="gericht-name">{g.get('name','')}</div>
            <div style="font-size:13px;color:#9b928b;margin:4px 0">{g.get('beschreibung','')}</div>
            <div class="gericht-preis">{preis}</div>
            <div style="margin-top:6px">{ampel}</div>
        </div>
        """, unsafe_allow_html=True)

    if not gerichte:
        st.markdown('<p style="color:#9b928b">Noch keine Gerichte eingetragen.</p>', unsafe_allow_html=True)

    bottom_nav()

# ─────────────────────────────────────────────
# SEITE 7: SICHERE ALTERNATIVEN
# ─────────────────────────────────────────────
def page_alternatives():
    st.markdown("# Sichere Alternativen")
    if st.session_state.user_allergene:
        st.caption("Gefiltert nach: " + " · ".join([ALLERGEN_SHORT[a] for a in st.session_state.user_allergene]))
    st.markdown("---")
    st.info("⚙️ Open Food Facts DB folgt in Phase 2.")
    import pandas as pd
    df = pd.DataFrame({
        "Produkt": ["Rote Linsen", "Kichererbsen", "Quinoa"],
        "Marke":   ["Ja! Natürlich", "Spar Bio", "dm Bio"],
        "Status":  ["✅ Sicher", "✅ Sicher", "✅ Sicher"]
    })
    st.dataframe(df, use_container_width=True)
    bottom_nav()

# ─────────────────────────────────────────────
# SEITE 8: PROFIL — reine HTML-Links, keine Button-Overlays
# ─────────────────────────────────────────────
def page_profil_uebersicht():
    st.markdown("# Profil")
    plan = "Plus" if is_premium() else "Gratistarif"

    # ── Sektion: Konto ──
    st.markdown('<div class="profil-section-title">Konto</div>', unsafe_allow_html=True)
    st.markdown(f"""
    <a href="?page=upgrade" class="profil-row" target="_self">
        <span class="profil-row-label">Abonnement</span>
        <span class="profil-row-right">
            <span class="profil-row-value">{plan}</span>
            <span class="profil-row-arrow">›</span>
        </span>
    </a>
    """, unsafe_allow_html=True)
    # FIX: Anmelden/Registrieren als Listenzeile unter Konto – kein Button, kein Heading
    if not st.session_state.user:
        st.markdown("""
        <a href="?page=auth" class="profil-row" target="_self">
            <span class="profil-row-label">Anmelden / Registrieren</span>
            <span class="profil-row-arrow">›</span>
        </a>
        """, unsafe_allow_html=True)

    # ── Sektion: App ──
    st.markdown('<div class="profil-section-title">App</div>', unsafe_allow_html=True)
    st.markdown("""
    <a href="?page=allergen_settings" class="profil-row" target="_self">
        <span class="profil-row-label">Meine Allergene</span>
        <span class="profil-row-arrow">›</span>
    </a>
    """, unsafe_allow_html=True)
    # Sprache: noch nicht navigierbar → nicht-klickbare Zeile (gedimmt)
    st.markdown("""
    <div class="profil-row">
        <span class="profil-row-label" style="color:#9b928b">Sprache</span>
        <span class="profil-row-right">
            <span class="profil-row-value">Deutsch</span>
            <span class="profil-row-arrow">›</span>
        </span>
    </div>
    """, unsafe_allow_html=True)

    # ── Abmelden (nur wenn eingeloggt) ──
    if st.session_state.user:
        st.markdown("<div style='margin-top:24px'></div>", unsafe_allow_html=True)
        def do_logout():
            supabase.auth.sign_out()
            for k in list(st.session_state.keys()):
                del st.session_state[k]
            st.rerun()
        st.button("🚪 Abmelden", on_click=do_logout)

    bottom_nav()

# ─────────────────────────────────────────────
# SEITE 9: UPGRADE
# ─────────────────────────────────────────────
def page_upgrade():
    st.markdown("# Hol dir Nuss-Checker Plus")
    st.markdown('<p style="color:#9b928b;font-size:14px">Alle Funktionen, keine Limits.</p>', unsafe_allow_html=True)
    st.markdown("---")

    # FIX Haken: display:inline-block statt display:block → text-align:center zentriert korrekt
    haken = f'<img src="data:image/svg+xml;base64,{ICON_HAKEN}" width="18px" style="display:inline-block;vertical-align:middle"/>'
    st.markdown(f"""
    <table class="upgrade-table">
        <thead>
            <tr>
                <th>Funktion</th>
                <th class="plan free">Free</th>
                <th class="plan plus">Plus</th>
            </tr>
        </thead>
        <tbody>
            <tr><td>Tägliche Scans</td><td class="center">3</td><td class="ja">∞</td></tr>
            <tr><td>Sichere Alternativen</td><td class="center">–</td><td class="ja">{haken}</td></tr>
            <tr><td>Lesezeichen</td><td class="center">–</td><td class="ja">{haken}</td></tr>
        </tbody>
    </table>
    """, unsafe_allow_html=True)

    st.markdown("---")
    # FIX: Pfeil → entfernt, use_container_width für volle Breite
    st.button("Upgrade für 2,99 €/Monat", type="primary", use_container_width=True, on_click=lambda: navigate("auth"))
    st.caption("⚙️ Zahlungsabwicklung via Stripe folgt in Phase 2.")
    bottom_nav()

# ─────────────────────────────────────────────
# SEITE 10: RESTAURANT ADMIN
# ─────────────────────────────────────────────
def page_restaurant_admin():
    st.markdown("# Restaurant-Verwaltung")

    if not st.session_state.restaurant_logged_in:
        st.markdown("## Login")
        email_r = st.text_input("E-Mail", key="rl_e")
        pw_r    = st.text_input("Passwort", type="password", key="rl_p")

        def do_rest_login():
            try:
                res = supabase.auth.sign_in_with_password({"email": email_r, "password": pw_r})
                rr = supabase.table("restaurants").select("*").eq("owner_id", res.user.id).single().execute()
                if rr.data:
                    st.session_state.restaurant_logged_in = True
                    st.session_state.restaurant_data = rr.data
                    st.session_state.user = res.user
                    st.rerun()
                else:
                    st.error("Kein Restaurant-Account gefunden.")
            except Exception as e:
                st.error(f"Login fehlgeschlagen: {e}")

        st.button("Einloggen", on_click=do_rest_login, type="primary")
    else:
        r = st.session_state.restaurant_data
        st.success(f"Eingeloggt als: **{r['name']}**")
        st.markdown("---")
        st.markdown("## Gericht hinzufügen")
        gericht_nr   = st.text_input("Gerichtnummer (z.B. 14 oder B2)")
        gericht_name = st.text_input("Name des Gerichts")
        beschreibung = st.text_area("Beschreibung")
        preis        = st.number_input("Preis (€)", min_value=0.0, step=0.5)
        st.markdown("**Enthaltene Allergene:**")
        cols = st.columns(4)
        allergen_sel = {}
        for i, (key, lbl) in enumerate(ALLERGEN_SHORT.items()):
            with cols[i % 4]:
                allergen_sel[key] = st.checkbox(f"{key}", key=f"adm_{key}", help=lbl)

        def save_gericht():
            try:
                supabase.table("gerichte").insert({
                    "restaurant_id": r["id"], "gericht_nummer": gericht_nr,
                    "name": gericht_name, "beschreibung": beschreibung,
                    "preis": preis, **allergen_sel
                }).execute()
                st.success("✅ Gericht gespeichert!")
            except Exception as e:
                st.error(f"Fehler: {e}")

        st.button("💾 Gericht speichern", on_click=save_gericht, type="primary")
        st.markdown("---")
        st.button("🚪 Ausloggen", on_click=lambda: [
            st.session_state.__setitem__("restaurant_logged_in", False),
            st.session_state.__setitem__("restaurant_data", None),
            navigate("profil_uebersicht")
        ])

    bottom_nav()

# ─────────────────────────────────────────────
# ROUTER
# ─────────────────────────────────────────────
routes = {
    "disclaimer":        page_disclaimer,
    "allergen_settings": page_allergen_settings,
    "auth":              page_auth,
    "scan":              page_scan,
    "restaurants":       page_restaurants,
    "speisekarte":       page_speisekarte,
    "alternatives":      page_alternatives,
    "profil_uebersicht": page_profil_uebersicht,
    "upgrade":           page_upgrade,
    "restaurant_admin":  page_restaurant_admin,
}

routes.get(st.session_state.page, page_scan)()
